apiVersion: v1
kind: Service
metadata:
  annotations:
    service.nlb.kube-dc.com/bind-on-default-gw-eip: "true"
  name: control-plane
  namespace: shalb-dev
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    cluster.x-k8s.io/role: control-plane
  type: LoadBalancer
