#!/bin/bash

# Save refresh token to a temporary file
REFRESH_TOKEN_FILE="/tmp/kube_dc_refresh_token"
echo "${REFRESH_TOKEN}" > "${REFRESH_TOKEN_FILE}"
chmod 600 "${REFRESH_TOKEN_FILE}"

SERVER_DOMAIN=$(echo "${SERVER_ENDPOINT}" | sed -E 's/https?:\/\///')

# Get base64 encoded CA certificate
export BASE64_ENCODED_CA_CERT=$(echo | openssl s_client -showcerts -connect ${SERVER_DOMAIN} 2>/dev/null | openssl x509 -outform PEM | base64 -w0)

# Use envsubst to replace placeholders and generate kubeconfig
envsubst < /usr/local/etc/kubeconfig.tmpl > "${KUBECONFIG}"

echo "Kubeconfig initialized"

/bin/bash
