name: cluster
template: "./templates/kube-dc/"
kind: Stack
backend: default
variables:
  debug: "true"
  kubeconfig: /home/arti/.kube/config

  monitoring:
    prom_storage: 20Gi
    retention_size: 17GiB
    retention: 365d
  
  cluster_config:
    default_gw_network_type: "cloud"
    default_eip_network_type: "public"
    default_fip_network_type: "public"
    default_svc_lb_network_type: "public"
    POD_CIDR: "10.100.0.0/16"
    POD_GATEWAY: "10.100.0.1"
    SVC_CIDR: "10.101.0.0/16"
    JOIN_CIDR: "172.30.0.0/22"
    cluster_dns: "10.101.0.11"
    default_external_network:
      type: cloud
      nodes_list:
        - kube-dc-master-1
        - kube-dc-worker-1
      name: ext-cloud
      vlan_id: "4013"
      interface: "enp0s31f6"
      cidr: "100.65.0.0/16"
      gateway: "100.65.0.1"
      mtu: "1400"
      exclude_ips: 
      - "100.65.0.1..100.65.0.100"
    
  node_external_ip: 88.99.29.250

  email: "noreply@shalb.com"
  domain: "stage.kube-dc.com"
  install_terraform: true
  kubeApiExternalUrl: "https://kube-api.stage.kube-dc.com:6443"

  create_default:
    organization:
      name: shalb
      description: "My test org my-org 1"
      email: "arti@shalb.com"
    project:
      name: demo
      cidr_block: "10.0.10.0/24"
      egress_network_type: cloud
   

  versions:
    kube_dc: "v0.1.31" # release version
    # kubevirt: "v1.3.0"
    # kubevirt_cdi: "v1.59.0"
    # cluster_api: "v1.8.1"
    # cluster_api_k3s_provider:  "v1.2.2"
    # kyverno: "v1.10.0"
    # terraform: "1.9.4"
    kube_ovn: "v1.13.13"
    # multus_helm: "2.2.9"
    # ingress_nginx_helm: "4.11.1"
    keycloak_helm: "24.3.0"
    prom_operator_helm: "67.4.0"
    # kube_dc: "v0.1.1-dev1"
    # cert_manager_helm: "v1.14.4"

    
