apiVersion: v1
kind: Service
metadata:
  name: kube-dc-ssh
  namespace: shalb-demo
  annotations:
    # service.nlb.kube-dc.com/bind-on-eip: nginx-dev
    service.nlb.kube-dc.com/bind-on-default-gw-eip: "true"
  labels:
    app: kube-dc
    component: ssh
spec:
  type: LoadBalancer
  selector:
    app: kube-dc
    component: ssh
    service: ssh-console
  ports:
    - name: ttyd
      protocol: TCP
      port: 7682
      targetPort: 7681