apiVersion: v1
kind: Secret
metadata:
  name: kube-dc-secret
  namespace: shalb-demo
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: kube-dc-kubectl
    uid: d729131d-f518-430e-ad3b-7acaa28d9f0c
type: Opaque
stringData:
  # Base64 encoded refresh token. DO NOT commit actual token value
  refresh_token: <base64_encoded_refresh_token>
