apiVersion: v1
kind: Secret
metadata:
  name: kube-dc-secret
  namespace: shalb-demo
type: Opaque
stringData:
  # Base64 encoded refresh token. DO NOT commit actual token value
  refresh_token: <REFRESH_TOKEN>
