{{- if .Values.dbManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-dc.dbmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-dc.dbmanager.labels" . | nindent 4 }}
{{- end }}
