{{- if .Values.dbManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-dc.dbmanager.fullname" . }}
  labels:
    {{- include "kube-dc.dbmanager.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
- apiGroups: [""]
  resources: [pods]
  verbs: [get, list, patch, watch]
- apiGroups: [""]
  resources: [secrets]
  verbs: [create, get, list, update, watch]
- apiGroups: [""]
  resources: [services]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [batch]
  resources: [jobs]
  verbs: [create, delete, get, list, watch]
- apiGroups: [db.kube-dc.com]
  resources: [kdcdatabases]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [db.kube-dc.com]
  resources: [kdcdatabases/finalizers]
  verbs: [update]
- apiGroups: [db.kube-dc.com]
  resources: [kdcdatabases/status]
  verbs: [get, patch, update]
- apiGroups: [gateway.envoyproxy.io]
  resources: [backends]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [gateway.networking.k8s.io]
  resources: [tlsroutes]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [k8s.mariadb.com]
  resources: [mariadbs, physicalbackups]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [k8s.mariadb.com]
  resources: [mariadbs/status]
  verbs: [get]
- apiGroups: [kube-dc.com]
  resources: [eips]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [kube-dc.com]
  resources: [projects]
  verbs: [get, list, watch]
- apiGroups: [objectbucket.io]
  resources: [objectbucketclaims]
  verbs: [create, delete, get, list, watch]
- apiGroups: [postgresql.cnpg.io]
  resources: [clusters, scheduledbackups]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [postgresql.cnpg.io]
  resources: [clusters/status]
  verbs: [get]
{{- end }}
