apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-dc.manager.serviceAccountName" . }}
  labels:
    {{- include "kube-dc.manager.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kube-dc.manager.labels" . | nindent 4 }}
  name: {{ include "kube-dc.manager.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-dc.manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
