package clusterinit

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// PlanSchemaVersion is the on-disk plan format version. Bumped only
// when the canonical-JSON shape changes in a way that breaks
// `--apply-plan` against an older file (e.g. a field renamed).
// `LoadPlan` refuses any non-matching value with `ErrPlanSchemaVersion`.
const PlanSchemaVersion = "v1"

// Plan is the deterministic snapshot of what `kube-dc bootstrap init`
// will do. Generated by `BuildPlan(opts)`, rendered for human review by
// `Render`, and reapplied verbatim by `--apply-plan <path>`.
//
// Determinism contract (installer-agentic-implementation-plan §9.M4-T02):
//
//   - Same `InitOptions` → byte-for-byte identical canonical JSON
//     (verified by `TestPlan_Deterministic` running BuildPlan twice).
//   - `InputHash` = SHA-256 of canonical-JSON `InitOptions`.
//   - `PlanHash`  = SHA-256 of canonical-JSON `Plan` with `PlanHash`
//     zeroed (so the hash doesn't depend on itself).
//
// Anti-determinism traps and how this file dodges them:
//
//   - Map iteration order: every map (Sets, NodeNICs, ScriptInvocation.Env)
//     is rendered via sorted keys. encoding/json already sorts map keys
//     alphabetically on marshal, so map fields are safe; we still sort
//     explicitly when iterating in Render so the textual output matches.
//   - Wall clock: `GeneratedAt` is NOT hashed; it's metadata. Two runs
//     with identical inputs produce identical canonical bytes even
//     across hours of separation.
//   - Slice ordering: slices preserve insertion order; BuildPlan is
//     responsible for sorting where order is semantically irrelevant
//     (e.g. SkippedExistingFleet). ScriptsToRun is ordered by execution
//     order — sorting THAT would corrupt the plan.
type Plan struct {
	// Version is the on-disk schema marker. Set to PlanSchemaVersion
	// at BuildPlan time; verified at LoadPlan time.
	Version string `json:"version"`

	// InputHash is the SHA-256 of the canonical-JSON `InitOptions`
	// the plan was derived from. `--apply-plan` recomputes this from
	// the current options and refuses with `ErrPlanInputDrift` on
	// mismatch — catches "I edited cluster-config.env between
	// dry-run and apply".
	InputHash string `json:"inputHash"`

	// PlanHash is the SHA-256 of this Plan's canonical-JSON
	// representation with `PlanHash` itself zeroed. Used as the
	// consent-cache key so `--no-tty` apply paths verify they're
	// applying exactly the plan the operator reviewed.
	PlanHash string `json:"planHash"`

	// GeneratedAt is metadata-only — NOT hashed (see type doc).
	GeneratedAt time.Time `json:"generatedAt"`

	// --- Inputs surfaced for the header block ---
	ClusterName string    `json:"clusterName"`
	Domain      string    `json:"domain"`
	FleetMode   FleetMode `json:"fleetMode"`
	Preset      Preset    `json:"preset"`
	Mode        Mode      `json:"mode"`

	// --- Detected from the fleet state ---
	// PriorClusters lists sibling cluster names when fleet-mode is
	// existing-fleet, used by the "Detected: existing-fleet" header.
	// Empty for new-repo / fresh installs.
	PriorClusters []string `json:"priorClusters,omitempty"`

	// InheritedDefaults are version pins (KUBE_DC_PLATFORM_VERSION,
	// chart versions, etc.) inherited from sibling clusters in
	// existing-fleet mode (M4-T13). Empty for greenfield installs.
	InheritedDefaults map[string]string `json:"inheritedDefaults,omitempty"`
	// InheritanceTemplate is the sibling cluster name whose values
	// won when siblings disagreed on a version pin (M4-T13's
	// "most-recently-modified template" rule). Surfaced in the
	// plan header so operators see which sibling drove the picks.
	InheritanceTemplate string `json:"inheritanceTemplate,omitempty"`

	// --- Action lists ---
	FilesToWrite          []PlanFile         `json:"filesToWrite"`
	ScriptsToRun          []ScriptInvocation `json:"scriptsToRun"`
	ClusterMutations      []Mutation         `json:"clusterMutations"`
	ConfirmationsRequired []Confirmation     `json:"confirmationsRequired"`
	SkippedExistingFleet  []string           `json:"skippedExistingFleet,omitempty"`
}

// PlanFile is one line in the "Files to write" preview. Path is
// relative to the fleet repo root; Description is the human label.
type PlanFile struct {
	Path        string `json:"path"`
	Description string `json:"description"`
	// Action is `+` (create), `~` (modify), or `-` (delete) — matches
	// the §5.3 text preview's left-column marker.
	Action string `json:"action"`
}

// ScriptInvocation describes one entry in the "Scripts to run"
// section. Index is 1-based execution order; DeferredUntil names a
// runtime gate when non-empty (e.g. "HelmRelease/openbao Ready").
type ScriptInvocation struct {
	Index         int               `json:"index"`
	Kind          string            `json:"kind"` // ports.ScriptKind string, or "(in-process)" for non-script steps
	Args          []string          `json:"args,omitempty"`
	Env           map[string]string `json:"env,omitempty"`
	DeferredUntil string            `json:"deferredUntil,omitempty"`
	Note          string            `json:"note,omitempty"`
}

// Mutation is one expected cluster-side change. Used by Render to
// produce the "Cluster mutations" block.
type Mutation struct {
	Kind      string `json:"kind"`
	Namespace string `json:"namespace,omitempty"`
	Name      string `json:"name"`
	Note      string `json:"note,omitempty"`
}

// Confirmation is one interactive prompt that the apply path needs to
// surface (TTY mode). `--yes` bypasses all of these.
type Confirmation struct {
	ID      string `json:"id"`
	Prompt  string `json:"prompt"`
	Default bool   `json:"default"`
}

// --- Errors ---

// ErrPlanInputDrift fires when --apply-plan recomputes InputHash from
// current InitOptions and gets a different value than the plan
// captured. The operator edited something between dry-run and apply.
var ErrPlanInputDrift = errors.New("init: applied plan inputs drifted from current --set / --node-nic / etc.")

// **Apply-plan verbatim contract** (M4-T04+T09+T13 review-pass — P2):
//
// The apply path (`--apply-plan <path>`) MUST consume the loaded
// `Plan` directly and MUST NOT re-derive fleet-state values
// (InheritedDefaults, PriorClusters, InheritanceTemplate) by
// re-calling `discoverFleetState` or `InheritFromSiblings` against
// the current repo. Sibling clusters can change between the
// operator's dry-run and apply (a coworker bumps `cloud`'s
// KUBE_DC_VERSION); re-deriving would silently change what gets
// written to the new cluster's cluster-config.env vs what the
// operator reviewed.
//
// What this means in practice for M4-T10..T12 engine slices:
//
//   - The engine takes a `*Plan` as input (NOT an
//     `*InitOptions` + a fresh `discoverFleetState` call).
//   - For `--apply-plan`, the cobra layer calls `LoadPlan` once
//     then hands the loaded Plan to the engine.
//   - For `--dry-run`+immediate-apply (`--yes` without
//     `--apply-plan`), the cobra layer calls `BuildPlan` once and
//     reuses that result; the engine still consumes the resulting
//     `*Plan`, not a freshly-discovered FleetState.
//
// `InputHash` covers the operator-supplied options (catches
// "I edited cluster-config.env between dry-run and apply").
// The verbatim contract above is what catches "a sibling changed
// underneath me" — by structural code shape rather than by
// recomputing a fleet-state hash, which would invalidate apply-
// plan on unrelated sibling tweaks.

// ErrPlanHashMismatch fires when LoadPlan recomputes PlanHash from the
// on-disk bytes and gets a different value than the plan claims.
// Indicates a corrupt or tampered plan file.
var ErrPlanHashMismatch = errors.New("init: plan file PlanHash doesn't match its content")

// ErrPlanSchemaVersion fires when LoadPlan reads a Version field that
// doesn't match PlanSchemaVersion. The user must re-dry-run with the
// current CLI to regenerate.
var ErrPlanSchemaVersion = errors.New("init: plan file schema version doesn't match the current CLI")

// ErrNoConsent fires when --no-tty is set without any of:
//   - --yes
//   - --apply-plan <path>
//   - a matching consent-cache marker from a prior --dry-run
//
// The cobra layer surfaces this with a help block listing the three
// options. Distinct from ErrApplyGate (the structural cobra check) —
// ErrNoConsent is engine-time, after consent-cache lookup.
var ErrNoConsent = errors.New("init: --no-tty without --yes / --apply-plan / matching --dry-run consent")

// --- Hashing + canonical JSON ---

// canonicalJSON marshals v to its determined canonical-JSON form:
// sorted keys (encoding/json does this for maps; struct field order is
// preserved which is fine because struct definitions don't change at
// runtime), no trailing newline, no escape-html. Used by both
// ComputeInputHash and the Plan.computeHash internal flow.
func canonicalJSON(v any) ([]byte, error) {
	// json.Marshal already sorts map keys but applies HTML escaping
	// by default; switch to Encoder so we can disable it (HTML escapes
	// are not stable across encoder versions and would silently break
	// hash equality if a default flipped).
	var buf strings.Builder
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	out := []byte(strings.TrimRight(buf.String(), "\n"))
	return out, nil
}

// hashHex returns the lowercase-hex SHA-256 of `data`. Kept as a
// helper so the hash algorithm can be changed in one place (a future
// schema bump might want a different hash).
func hashHex(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// inputsForHash is the projection of InitOptions that participates in
// InputHash. Two categories of fields are deliberately excluded:
//
//  1. **Apply-flow flags** — DryRun, ApplyPlan, PlanFile, Yes, NoTTY,
//     NoPush differ between dry-run and apply runs by design (operator
//     runs --dry-run, then --apply-plan with --yes), so including them
//     would make every apply-plan fail with ErrPlanInputDrift.
//
//  2. **Execution-time credentials** — GitHubToken (M4-T01+T02
//     review-pass — P2). A token is auth material, not a *substantive*
//     plan input; what the plan does doesn't depend on which token is
//     used. Including it means rotating tokens or switching between
//     --github-token=... and the `gh auth token` resolution path would
//     break --apply-plan even when the plan is otherwise identical.
//     It's also poor secret hygiene to derive a persisted hash from a
//     credential — the hash is not reversible, but any token-derived
//     artefact is best avoided. The cobra layer still validates token
//     availability at apply time, just not via the plan hash.
//
// Everything else — the substantive inputs that determine what the
// plan does — is included.
//
// Field order is fixed (struct field order = encoding/json key order)
// so the hash is deterministic. Adding a new substantive field to
// InitOptions means adding it here too; the
// TestComputeInputHash_SensitiveToChange table guards the
// "meaningful field changes the hash" invariant.
type inputsForHash struct {
	Preset           Preset            `json:"preset"`
	Mode             Mode              `json:"mode"`
	Name             string            `json:"name"`
	Domain           string            `json:"domain"`
	NodeExternalIP   string            `json:"nodeExternalIp"`
	Email            string            `json:"email"`
	FleetMode        FleetMode         `json:"fleetMode"`
	Repo             string            `json:"repo"`
	GitHubOwner      string            `json:"githubOwner"`
	GitHubRepo       string            `json:"githubRepo"`
	Sets             map[string]string `json:"sets,omitempty"`
	NodeNICs         map[string]string `json:"nodeNics,omitempty"`
	RookMode         RookMode          `json:"rookMode"`
	RookOSDNode      string            `json:"rookOsdNode"`
	RookOSDSizeGB    int               `json:"rookOsdSizeGb"`
	Addons           []string          `json:"addons,omitempty"`
	AllowDNSNotReady        bool `json:"allowDnsNotReady"`
	AllowNoKubevirtEligible bool `json:"allowNoKubevirtEligible"`
	SSHHost          string            `json:"sshHost"`
	NoSSH            bool              `json:"noSsh"`
	NoInstallPrereqs bool              `json:"noInstallPrereqs"`
	NoCreateRepo     bool              `json:"noCreateRepo"`
	MirrorRegistry   string            `json:"mirrorRegistry"`
	BundlePullSecret string            `json:"bundlePullSecret"`
	OpenBaoSharesOut string            `json:"openbaoSharesOut"`
}

func (o *InitOptions) inputsForHash() inputsForHash {
	return inputsForHash{
		Preset:           o.Preset,
		Mode:             o.Mode,
		Name:             o.Name,
		Domain:           o.Domain,
		NodeExternalIP:   o.NodeExternalIP,
		Email:            o.Email,
		FleetMode:        o.FleetMode,
		Repo:             o.Repo,
		GitHubOwner:      o.GitHubOwner,
		GitHubRepo:       o.GitHubRepo,
		Sets:             o.Sets,
		NodeNICs:         o.NodeNICs,
		RookMode:         o.RookMode,
		RookOSDNode:      o.RookOSDNode,
		RookOSDSizeGB:    o.RookOSDSizeGB,
		Addons:           o.Addons,
		AllowDNSNotReady:        o.AllowDNSNotReady,
		AllowNoKubevirtEligible: o.AllowNoKubevirtEligible,
		SSHHost:          o.SSHHost,
		NoSSH:            o.NoSSH,
		NoInstallPrereqs: o.NoInstallPrereqs,
		NoCreateRepo:     o.NoCreateRepo,
		MirrorRegistry:   o.MirrorRegistry,
		BundlePullSecret: o.BundlePullSecret,
		OpenBaoSharesOut: o.OpenBaoSharesOut,
	}
}

// ComputeInputHash returns the SHA-256 of canonical-JSON of the
// **substantive** subset of `o` — see `inputsForHash` doc for the
// exclusion list (apply-flow flags + execution-time credentials).
// Stable across runs + platforms.
func ComputeInputHash(o *InitOptions) (string, error) {
	if o == nil {
		return "", fmt.Errorf("ComputeInputHash: nil options")
	}
	data, err := canonicalJSON(o.inputsForHash())
	if err != nil {
		return "", fmt.Errorf("canonical-JSON options: %w", err)
	}
	return hashHex(data), nil
}

// computeHash returns the SHA-256 of `p` with the metadata-only
// fields zeroed (`PlanHash` and `GeneratedAt`). Used internally by
// BuildPlan (to set PlanHash) and by LoadPlan (to verify the
// on-disk value).
//
// **Why GeneratedAt is zeroed** (M4-T01+T02 review-pass — P1): the
// Plan type doc declares "GeneratedAt is NOT hashed; it's metadata."
// Earlier `computeHash` only zeroed `PlanHash`, so two BuildPlans
// from the same inputs at different seconds produced different
// PlanHash values — a silent determinism bug that undermined the
// hash-pinning safety contract. Zeroing here restores the
// documented invariant; `TestPlan_PlanHashExcludesGeneratedAt`
// guards against regression by forcing two plans with different
// `GeneratedAt` values and asserting identical PlanHash.
func (p *Plan) computeHash() (string, error) {
	clone := *p
	clone.PlanHash = ""
	clone.GeneratedAt = time.Time{}
	data, err := canonicalJSON(&clone)
	if err != nil {
		return "", fmt.Errorf("canonical-JSON plan: %w", err)
	}
	return hashHex(data), nil
}

// --- BuildPlan ---

// FleetState is the subset of "what the fleet repo looks like right
// now" that plan generation needs. The cobra layer populates this
// from `discover.ListClusters` + `clusterinit.InheritFromSiblings`
// (M4-T13); tests build it directly with hand-crafted siblings.
type FleetState struct {
	// PriorClusters lists existing `clusters/<name>/` overlays.
	// Empty for new-repo greenfield installs.
	PriorClusters []string
	// SOPSRecipients is the count of `.sops.yaml` recipients in
	// existing-fleet mode; the plan-render uses this for the "12
	// keys; encrypted to N recipients" line.
	SOPSRecipients int
	// PlatformVersion is the legacy single-version pin previously
	// surfaced in the plan header. Kept for one release as a
	// fallback when `InheritedDefaults` doesn't carry
	// KUBE_DC_PLATFORM_VERSION; new callers should pass siblings +
	// rely on InheritedDefaults instead.
	//
	// Deprecated: populate `Siblings` and let BuildPlan derive
	// inheritance from them.
	PlatformVersion string

	// Siblings is the full sibling-cluster list with parsed envs +
	// ModTimes. M4-T13's `InheritFromSiblings` consumes this to
	// derive the version-pin defaults; the cobra layer fills it
	// from disk before BuildPlan runs.
	Siblings []SiblingCluster
	// InheritedDefaults is the merged version-pin map from
	// InheritFromSiblings — pre-computed so BuildPlan doesn't have
	// to walk Siblings again. Empty for greenfield / new-repo.
	InheritedDefaults map[string]string
	// InheritanceTemplate is the sibling whose values won when
	// siblings disagreed (from InheritanceResult.TemplateName).
	// Rendered in the "Detected: existing-fleet → using <name>"
	// header line.
	InheritanceTemplate string
}

// BuildPlan derives the deterministic Plan from validated options +
// fleet state. Sorts everything order-irrelevant; preserves
// execution-order slices verbatim; fills both hashes.
//
// **Scope of T02**: the file/script enumeration is the
// canonical-§5.3/§5.5 skeleton. T04 (presets), T10 (scaffold), T11
// (customInterfaces), T12 (commit/push/flux), T13 (existing-fleet
// inheritance) will replace these placeholders with engine-derived
// values. Operators dry-running today see what they'll see at first
// apply once those slices ship — only the "exact line count" preview
// values are placeholders.
func BuildPlan(o *InitOptions, fleet FleetState) (*Plan, error) {
	if o == nil {
		return nil, fmt.Errorf("BuildPlan: nil options")
	}
	if err := o.Validate(); err != nil {
		return nil, fmt.Errorf("BuildPlan: %w", err)
	}

	inputHash, err := ComputeInputHash(o)
	if err != nil {
		return nil, err
	}

	p := &Plan{
		Version:     PlanSchemaVersion,
		InputHash:   inputHash,
		GeneratedAt: time.Now().UTC().Truncate(time.Second),
		ClusterName: o.Name,
		Domain:      o.Domain,
		FleetMode:   o.FleetMode,
		Preset:      o.Preset,
		Mode:        o.Mode,
	}

	if o.FleetMode == FleetExistingFleet {
		sorted := append([]string(nil), fleet.PriorClusters...)
		sort.Strings(sorted)
		p.PriorClusters = sorted
		// M4-T13 + review-pass P3: defensive-copy the
		// InheritedDefaults map so a caller mutating
		// `fleet.InheritedDefaults` after BuildPlan returns can't
		// silently corrupt the plan's contents without the
		// PlanHash detecting it (since the hash was computed
		// before the mutation). The plan owns its own copy.
		switch {
		case len(fleet.InheritedDefaults) > 0:
			cp := make(map[string]string, len(fleet.InheritedDefaults))
			for k, v := range fleet.InheritedDefaults {
				cp[k] = v
			}
			p.InheritedDefaults = cp
		case fleet.PlatformVersion != "":
			p.InheritedDefaults = map[string]string{
				"KUBE_DC_PLATFORM_VERSION": fleet.PlatformVersion,
			}
		}
		p.InheritanceTemplate = fleet.InheritanceTemplate
	}

	p.FilesToWrite = filesForOptions(o, fleet)
	p.ScriptsToRun = scriptsForOptions(o, fleet)
	p.ClusterMutations = mutationsForOptions(o)
	p.ConfirmationsRequired = confirmationsForOptions(o)
	p.SkippedExistingFleet = skippedForOptions(o, fleet)

	hash, err := p.computeHash()
	if err != nil {
		return nil, err
	}
	p.PlanHash = hash
	return p, nil
}

// filesForOptions returns the deterministic "Files to write" list.
// T04 wired the preset's Kustomization list + env-map size into the
// descriptions; T10 will refine further when the actual scaffold
// engine writes the files.
func filesForOptions(o *InitOptions, fleet FleetState) []PlanFile {
	base := o.Name + "/"

	// Derive the cluster-config.env line count from the preset's
	// resolved env map. Operators see "(42 keys)" rather than a
	// generic placeholder — catches "I missed a --set" before
	// scrolling through the deferred T10 file.
	envKeyCount := 0
	if envMap, err := EnvMapFor(o.Preset, o.Sets); err == nil {
		envKeyCount = len(envMap)
	}
	envDesc := "cluster-config.env"
	if envKeyCount > 0 {
		envDesc = fmt.Sprintf("cluster-config.env (%d keys, preset=%s)", envKeyCount, o.Preset)
	}

	// Compose the infrastructure.yaml description from the preset's
	// Kustomization layer set (T04). Cloudacropolis's
	// cloud+public-vlan adds infra-public-network; internal-only
	// omits it. Listing the actual layers makes the dry-run
	// self-documenting for operators reviewing a CI plan.
	infraLayers := infrastructureLayers(o.Preset)
	infraDesc := "infrastructure.yaml"
	if len(infraLayers) > 0 {
		infraDesc = fmt.Sprintf("infrastructure.yaml (%s)", strings.Join(infraLayers, " + "))
	}

	files := []PlanFile{
		{Path: "clusters/" + base + "cluster-config.env", Description: envDesc, Action: "+"},
		{Path: "clusters/" + base + "secrets.enc.yaml", Description: "secrets.enc.yaml (SOPS-encrypted)", Action: "+"},
		{Path: "clusters/" + base + "kustomization.yaml", Description: "kustomization.yaml (Flux entry)", Action: "+"},
		{Path: "clusters/" + base + "infrastructure.yaml", Description: infraDesc, Action: "+"},
		{Path: "clusters/" + base + "infra-object-storage.yaml", Description: "infra-object-storage Kustomization", Action: "+"},
		{Path: "clusters/" + base + "platform.yaml", Description: "platform Kustomization", Action: "+"},
		{Path: "clusters/" + base + "addons.yaml", Description: "addons Kustomization", Action: "+"},
	}
	if o.RookMode != RookDisabled {
		files = append(files, PlanFile{
			Path:        "clusters/" + base + "object-storage/",
			Description: "object-storage overlay (Rook " + string(o.RookMode) + ")",
			Action:      "+",
		})
	}
	if len(o.Addons) > 0 {
		files = append(files, PlanFile{
			Path:        "clusters/" + base + "addons/",
			Description: "addons overlay (" + strings.Join(o.Addons, ", ") + ")",
			Action:      "+",
		})
	}
	// Stable order — Files-to-Write preserves the §5.3 reading order
	// (config → secrets → flux entries → overlays); no need to sort.
	return files
}

// infrastructureLayers returns the Kustomization names that
// `infrastructure.yaml` references for the given preset. The list
// is filtered to the "infra-*" layers only (object-storage /
// platform / addons live in their own files); ordering matches the
// preset spec.
func infrastructureLayers(p Preset) []string {
	all, ok := PresetKustomizations(p)
	if !ok {
		return nil
	}
	var out []string
	for _, k := range all {
		if strings.HasPrefix(k, "infra-") && k != "infra-object-storage" {
			out = append(out, k)
		}
	}
	return out
}

// scriptsForOptions enumerates the run-order steps. Indexes are
// 1-based and assigned monotonically. T10/T12 will refine the actual
// args (e.g. `bootstrap/add-cluster.sh` takes positional args from
// InitOptions); T02 surfaces the canonical step list.
func scriptsForOptions(o *InitOptions, fleet FleetState) []ScriptInvocation {
	scripts := []ScriptInvocation{}
	idx := 0
	add := func(s ScriptInvocation) {
		idx++
		s.Index = idx
		scripts = append(scripts, s)
	}

	// Greenfield-only steps that existing-fleet skips.
	if o.FleetMode != FleetExistingFleet {
		add(ScriptInvocation{Kind: "bootstrap/generate-age-key.sh", Note: "only if age.key missing"})
		add(ScriptInvocation{Kind: "(in-process) extract fleet-starter OCI bundle", Note: "M4-T10"})
	}

	if o.FleetMode != FleetExistingFleet {
		add(ScriptInvocation{
			Kind: "bootstrap/add-cluster.sh",
			Args: []string{o.Name, o.Domain, o.NodeExternalIP},
			Note: "scaffolds clusters/" + o.Name + "/",
		})
	} else {
		add(ScriptInvocation{
			Kind: "(in-process) scaffold from sibling templates",
			Note: "existing-fleet — refuses if clusters/" + o.Name + "/ already exists",
		})
	}

	add(ScriptInvocation{
		Kind: "(in-process) apply form deltas to cluster-config.env",
		Note: "the --set values; preserves key order",
	})
	if len(o.NodeNICs) > 0 {
		add(ScriptInvocation{
			Kind: "(in-process) render customInterfaces into infrastructure.yaml",
			Note: fmt.Sprintf("%d --node-nic mapping(s)", len(o.NodeNICs)),
		})
	}
	add(ScriptInvocation{
		Kind: "(in-process) sops encrypt clusters/" + o.Name + "/secrets.enc.yaml",
		Note: sopsRecipientsNote(fleet),
	})
	if !o.NoPush {
		add(ScriptInvocation{
			Kind: "(in-process) git add + commit + push",
			Note: "atomic — push failure rolls back the commit",
		})
	}
	add(ScriptInvocation{
		Kind: "bootstrap/flux-install.sh",
		Args: []string{o.Name, "--new-cluster"},
		Note: "wires Flux + applies the new cluster Kustomization",
	})

	// Deferred steps after Flux brings up the components.
	add(ScriptInvocation{
		Kind:          "kube-dc bootstrap openbao init",
		Args:          []string{o.Name},
		DeferredUntil: "HelmRelease/openbao Ready",
		Note:          "share-custody gate (5 shares + root token, fully automated)",
	})
	add(ScriptInvocation{
		Kind:          "hack/openbao-setup-controller-auth.sh",
		DeferredUntil: "OpenBao unsealed",
		Note:          "installs the k8s-host auth method + controller policies",
	})
	add(ScriptInvocation{
		Kind:          "bootstrap/setup-keycloak-oidc.sh",
		Args:          []string{o.Name},
		DeferredUntil: "HelmRelease/keycloak Ready",
	})
	if o.RookMode != RookDisabled {
		add(ScriptInvocation{
			Kind:          "(in-process) apply Rook CephObjectStore + system OBCs",
			DeferredUntil: "CephCluster.phase=Ready",
		})
	}
	return scripts
}

func sopsRecipientsNote(fleet FleetState) string {
	if fleet.SOPSRecipients == 0 {
		return "single recipient (operator's local age key)"
	}
	return fmt.Sprintf("recipients auto-resolved from .sops.yaml: %d age key(s)", fleet.SOPSRecipients)
}

// mutationsForOptions returns the canonical cluster-side mutations.
// T12 will refine with actual GVR shapes; T02 surfaces the
// installer-prd §5.3 baseline.
func mutationsForOptions(o *InitOptions) []Mutation {
	return []Mutation{
		{Kind: "Namespace", Name: "flux-system"},
		{Kind: "GitRepository", Namespace: "flux-system", Name: "flux-system", Note: "gotk-sync"},
		{Kind: "Kustomization", Namespace: "flux-system", Name: "flux-system", Note: "gotk-sync entry pointing at clusters/" + o.Name},
		{Kind: "Secret", Namespace: "flux-system", Name: "sops-age", Note: "age private key (operator's local key)"},
	}
}

func confirmationsForOptions(o *InitOptions) []Confirmation {
	// Per installer-ux §5.3, OpenBao share custody is fully automated
	// — no interactive gate. The only TTY confirmation is the final
	// "apply plan?" prompt, which --yes / --apply-plan / --dry-run
	// also bypass. Return an empty list explicitly so the plan's
	// "Confirmations required" section renders the "(none)" line.
	_ = o
	return []Confirmation{}
}

// skippedForOptions returns the "Files NOT touched" / "Skipped" list
// for existing-fleet renders. Empty for new-repo.
func skippedForOptions(o *InitOptions, fleet FleetState) []string {
	if o.FleetMode != FleetExistingFleet {
		return nil
	}
	skipped := []string{
		"infrastructure/ (shared base — managed by OCI bundle)",
		"platform/ (shared base)",
		"addons/ (shared base)",
		".sops.yaml (already includes operator's pubkey)",
	}
	for _, name := range fleet.PriorClusters {
		skipped = append(skipped, "clusters/"+name+"/ (untouched)")
	}
	sort.Strings(skipped)
	return skipped
}

// --- Render ---

// Render writes the human-readable plan preview to w. The shape
// mirrors installer-ux §5.3 (greenfield) and §5.5 (existing-fleet).
// Existing-fleet adds the "Detected: existing-fleet at . " header +
// "Files NOT touched" section.
func (p *Plan) Render(w io.Writer) {
	if p.FleetMode == FleetExistingFleet {
		fmt.Fprintln(w, "== Detected: existing-fleet ==")
		if len(p.PriorClusters) > 0 {
			fmt.Fprintf(w, "   Prior clusters: %s\n", strings.Join(p.PriorClusters, ", "))
		}
		if p.InheritanceTemplate != "" {
			fmt.Fprintf(w, "   Template (most-recently-modified sibling): %s\n", p.InheritanceTemplate)
		}
		if len(p.InheritedDefaults) > 0 {
			fmt.Fprintf(w, "   Inherited defaults (%d version pins; override with --set):\n", len(p.InheritedDefaults))
			keys := make([]string, 0, len(p.InheritedDefaults))
			for k := range p.InheritedDefaults {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				fmt.Fprintf(w, "     %s=%s\n", k, p.InheritedDefaults[k])
			}
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintf(w, "== Files to write (clusters/%s/) ==\n", p.ClusterName)
	for _, f := range p.FilesToWrite {
		fmt.Fprintf(w, " %s %s — %s\n", f.Action, f.Path, f.Description)
	}

	if len(p.SkippedExistingFleet) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "== Files NOT touched (already in fleet) ==")
		for _, s := range p.SkippedExistingFleet {
			fmt.Fprintf(w, " - %s\n", s)
		}
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "== Scripts to run ==")
	for _, s := range p.ScriptsToRun {
		marker := ""
		if s.DeferredUntil != "" {
			marker = " (deferred until " + s.DeferredUntil + ")"
		}
		args := ""
		if len(s.Args) > 0 {
			args = " " + strings.Join(s.Args, " ")
		}
		fmt.Fprintf(w, " [%2d] %s%s%s\n", s.Index, s.Kind, args, marker)
		if s.Note != "" {
			fmt.Fprintf(w, "      %s\n", s.Note)
		}
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "== Cluster mutations ==")
	for _, m := range p.ClusterMutations {
		ns := ""
		if m.Namespace != "" {
			ns = m.Namespace + "/"
		}
		note := ""
		if m.Note != "" {
			note = " — " + m.Note
		}
		fmt.Fprintf(w, " + %s/%s%s%s\n", m.Kind, ns, m.Name, note)
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "== Confirmations required ==")
	if len(p.ConfirmationsRequired) == 0 {
		fmt.Fprintln(w, " (none in --no-tty mode; --yes applies the full plan unattended)")
		fmt.Fprintln(w, " (TTY mode: one final \"apply plan? [y/N]\" prompt before mutations start)")
	}
	for _, c := range p.ConfirmationsRequired {
		def := "n"
		if c.Default {
			def = "y"
		}
		fmt.Fprintf(w, " - %s: %s [%s]\n", c.ID, c.Prompt, def)
	}

	fmt.Fprintln(w)
	fmt.Fprintf(w, "Plan: %d scripts, %d files, %d cluster mutations, 0 destructive gates.\n",
		len(p.ScriptsToRun), len(p.FilesToWrite), len(p.ClusterMutations))
	fmt.Fprintf(w, "InputHash: %s\nPlanHash:  %s\n", p.InputHash, p.PlanHash)
	fmt.Fprintln(w, "Pass --yes to apply, --apply-plan <plan.json> to apply hash-pinned.")
}

// --- File I/O ---

// WritePlanFile atomically writes `p`'s canonical JSON to `path`.
//
// Atomicity contract:
//
//   - Writes to a unique temp file via `os.CreateTemp(dir, base+".*.tmp")`
//     so concurrent writes to the same destination don't collide
//     (M4-T01+T02 review-pass — P3).
//   - Renames the temp file into place; the rename is atomic on POSIX
//     filesystems within the same directory.
//   - On failure at any step, the temp file is removed; the
//     destination is never partially-written.
//
// Mode 0644 — the plan contains no secret material since InputHash
// is a one-way hash and GitHubToken is excluded from the hash
// projection (see `inputsForHash` doc).
func WritePlanFile(p *Plan, path string) error {
	data, err := canonicalJSON(p)
	if err != nil {
		return fmt.Errorf("canonical-JSON plan: %w", err)
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	// Unique temp file in the destination directory (same FS so the
	// rename is atomic on POSIX). Pattern `<base>.*.tmp` keeps the
	// suffix predictable for debugging — `.*` is replaced with a
	// random token by os.CreateTemp.
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".*.tmp")
	if err != nil {
		return fmt.Errorf("create temp in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	if _, werr := tmp.Write(data); werr != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("write temp %s: %w", tmpPath, werr)
	}
	// Match the old behaviour: world-readable, owner-writable. CreateTemp
	// defaults to 0600 — we explicitly broaden to 0644 because the
	// plan is not secret and operators may want to inspect it
	// without sudo (the .tmp file is short-lived but the rename
	// inherits the mode).
	if err := tmp.Chmod(0o644); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("chmod temp %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("close temp %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("rename %s -> %s: %w", tmpPath, path, err)
	}
	return nil
}

// LoadPlan reads the plan JSON from `path` and verifies both the
// schema version and the PlanHash. Returns ErrPlanSchemaVersion or
// ErrPlanHashMismatch on tamper/version drift.
func LoadPlan(path string) (*Plan, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read plan %s: %w", path, err)
	}
	var p Plan
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parse plan %s: %w", path, err)
	}
	if p.Version != PlanSchemaVersion {
		return nil, fmt.Errorf("%w (got %q, want %q)", ErrPlanSchemaVersion, p.Version, PlanSchemaVersion)
	}
	want, err := p.computeHash()
	if err != nil {
		return nil, fmt.Errorf("verify plan hash: %w", err)
	}
	if want != p.PlanHash {
		return nil, fmt.Errorf("%w (computed %s, file %s)", ErrPlanHashMismatch, want, p.PlanHash)
	}
	return &p, nil
}

// VerifyApplyPlanInput recomputes InputHash from `o` and compares to
// `p.InputHash`. Returns ErrPlanInputDrift on mismatch.
func VerifyApplyPlanInput(p *Plan, o *InitOptions) error {
	want, err := ComputeInputHash(o)
	if err != nil {
		return err
	}
	if want != p.InputHash {
		return fmt.Errorf("%w (plan inputHash=%s; current=%s)", ErrPlanInputDrift, p.InputHash, want)
	}
	return nil
}

// --- Consent cache ---

// ConsentMarker is the small JSON file that a successful --dry-run
// writes to ~/.kube-dc/init-state/<cluster>-dry-run-ok.json. It is
// not a resume token — purely a local "yes, this exact plan was just
// reviewed" signal so `--no-tty` apply can proceed without --yes.
type ConsentMarker struct {
	ClusterName string    `json:"clusterName"`
	PlanHash    string    `json:"planHash"`
	GeneratedAt time.Time `json:"generatedAt"`
}

// ConsentMarkerPath returns the canonical on-disk path for a cluster's
// consent marker. Indirected through a package var so tests can
// substitute a tmpdir.
var consentDir = func() string {
	if home, err := os.UserHomeDir(); err == nil {
		return filepath.Join(home, ".kube-dc", "init-state")
	}
	return os.TempDir()
}

func ConsentMarkerPath(cluster string) string {
	// Cluster names can contain '/' (cs/zrh shape) — flatten so the
	// marker file is one path component.
	safe := strings.ReplaceAll(cluster, "/", "_")
	return filepath.Join(consentDir(), safe+"-dry-run-ok.json")
}

// WriteConsentMarker writes the marker for a freshly-dry-run plan.
// Existing marker is overwritten (a fresh dry-run is the latest
// consent). Uses the same unique-temp + rename pattern as
// WritePlanFile so concurrent dry-runs of distinct clusters can't
// collide on the temp suffix.
func WriteConsentMarker(p *Plan) error {
	m := ConsentMarker{
		ClusterName: p.ClusterName,
		PlanHash:    p.PlanHash,
		GeneratedAt: time.Now().UTC().Truncate(time.Second),
	}
	data, err := json.Marshal(m)
	if err != nil {
		return fmt.Errorf("marshal consent marker: %w", err)
	}
	path := ConsentMarkerPath(p.ClusterName)
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".*.tmp")
	if err != nil {
		return fmt.Errorf("create temp in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	if _, werr := tmp.Write(data); werr != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("write %s: %w", tmpPath, werr)
	}
	if err := tmp.Chmod(0o644); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("chmod %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("close %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("rename %s -> %s: %w", tmpPath, path, err)
	}
	return nil
}

// LookupConsentMarker reads the marker for `cluster` and reports
// whether its PlanHash matches `wantHash`. Returns (false, nil) if no
// marker exists; (false, err) on parse/IO failure; (true, nil) on
// match. A non-match is (false, nil) so the cobra layer can surface a
// clean "no consent for this plan; re-run --dry-run" message rather
// than a stack trace.
func LookupConsentMarker(cluster, wantHash string) (bool, error) {
	path := ConsentMarkerPath(cluster)
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("read consent marker %s: %w", path, err)
	}
	var m ConsentMarker
	if err := json.Unmarshal(data, &m); err != nil {
		return false, fmt.Errorf("parse consent marker %s: %w", path, err)
	}
	return m.PlanHash == wantHash, nil
}
