package clusterinit

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// PlanSchemaVersion is the on-disk plan format version. Bumped only
// when the canonical-JSON shape changes in a way that breaks
// `--apply-plan` against an older file (e.g. a field renamed).
// `LoadPlan` refuses any non-matching value with `ErrPlanSchemaVersion`.
//
// v2 (OS-1, 2026-07-04): Plan grew `Warnings`; inputsForHash grew the
// object-storage companion fields; object-storage mode became a
// required input. An old binary reading a v2 plan would silently drop
// Warnings and fail with a confusing hash mismatch — the version bump
// converts that into the honest "re-run dry-run with this CLI" error.
//
// v3 (GPU installer, 2026-07-15): inputsForHash gained the accelerator
// platform/source/version/node-mode/profile and secret-readiness contract.
// Older binaries must not apply a reviewed GPU plan after dropping those fields.
//
// v4 (private-CA installer, 2026-07-27): the plan binds the reviewed CA
// bundle fingerprint and lists its durable ConfigMap artifact.
// v5 (2026-08-09): the greenfield file list became address-layer-conditional
// (a layer=none plan no longer promises the four MetalLB scaffold files the
// apply never writes). A v4 plan saved by an older CLI still LISTS those
// files, and replaying it through --apply-plan would pass its own stored-hash
// validation while the apply omits what the operator approved — the exact
// drift the verbatim contract exists to prevent. Bumping the schema forces a
// re-dry-run with the current CLI instead.
const PlanSchemaVersion = "v5"

// Plan is the deterministic snapshot of what `kube-dc bootstrap init`
// will do. Generated by `BuildPlan(opts)`, rendered for human review by
// `Render`, and reapplied verbatim by `--apply-plan <path>`.
//
// Determinism contract (installer-agentic-implementation-plan §9.M4-T02):
//
//   - Same `InitOptions` → byte-for-byte identical canonical JSON
//     (verified by `TestPlan_Deterministic` running BuildPlan twice).
//   - `InputHash` = SHA-256 of canonical-JSON `InitOptions`.
//   - `PlanHash`  = SHA-256 of canonical-JSON `Plan` with `PlanHash`
//     zeroed (so the hash doesn't depend on itself).
//
// Anti-determinism traps and how this file dodges them:
//
//   - Map iteration order: every map (Sets, NodeNICs, ScriptInvocation.Env)
//     is rendered via sorted keys. encoding/json already sorts map keys
//     alphabetically on marshal, so map fields are safe; we still sort
//     explicitly when iterating in Render so the textual output matches.
//   - Wall clock: `GeneratedAt` is NOT hashed; it's metadata. Two runs
//     with identical inputs produce identical canonical bytes even
//     across hours of separation.
//   - Slice ordering: slices preserve insertion order; BuildPlan is
//     responsible for sorting where order is semantically irrelevant
//     (e.g. SkippedExistingFleet). ScriptsToRun is ordered by execution
//     order — sorting THAT would corrupt the plan.
type Plan struct {
	// Version is the on-disk schema marker. Set to PlanSchemaVersion
	// at BuildPlan time; verified at LoadPlan time.
	Version string `json:"version"`

	// InputHash is the SHA-256 of the canonical-JSON `InitOptions`
	// the plan was derived from. `--apply-plan` recomputes this from
	// the current options and refuses with `ErrPlanInputDrift` on
	// mismatch — catches "I edited cluster-config.env between
	// dry-run and apply".
	InputHash string `json:"inputHash"`

	// PlanHash is the SHA-256 of this Plan's canonical-JSON
	// representation with `PlanHash` itself zeroed. Used as the
	// consent-cache key so `--no-tty` apply paths verify they're
	// applying exactly the plan the operator reviewed.
	PlanHash string `json:"planHash"`

	// GeneratedAt is metadata-only — NOT hashed (see type doc).
	GeneratedAt time.Time `json:"generatedAt"`

	// --- Inputs surfaced for the header block ---
	ClusterName string    `json:"clusterName"`
	Domain      string    `json:"domain"`
	FleetMode   FleetMode `json:"fleetMode"`
	StarterRef  string    `json:"starterRef"`
	// OpenBaoSharesOut is a local custody destination, not secret material.
	// It is surfaced so a reviewer can verify where the automatic ceremony writes.
	OpenBaoSharesOut string `json:"openbaoSharesOut,omitempty"`
	// TLSMode ("" = acme) + the reviewed leaf's hex SHA-256. Surfaced on the
	// plan header so the reviewer sees WHICH certificate ships; apply refuses
	// material whose fingerprint differs. Both also participate in InputHash.
	TLSMode            string `json:"tlsMode,omitempty"`
	TLSCertFingerprint string `json:"tlsCertFingerprint,omitempty"`
	// DNS01SecretKeyFingerprint (hex SHA-256 of the AWS secret access key)
	// binds an acme-dns01-route53 plan to the exact credential that ships,
	// mirroring TLSCertFingerprint. High-entropy input, so the digest is safe
	// to surface.
	DNS01SecretKeyFingerprint string `json:"dns01SecretKeyFingerprint,omitempty"`
	// Front door (design v2 §5a). These live on the PLAN, not just in the
	// hash: the scaffold derives the Envoy service shape from the layer, so
	// apply must ship the layer the operator REVIEWED. Without it here, a
	// reviewed metallb-l2 plan silently scaffolded as none/ClusterIP — the
	// flag is a dedicated field and is rejected via --set, so o.Sets never
	// carried it into EnvMapFor (codex 2026-08-07, P1).
	// IngressAddressLayer is the RESOLVED layer, not the raw flag: a plan is
	// a statement of what will be BUILT, so an operator who passed nothing
	// must still see "none" here rather than a blank they have to interpret.
	IngressAddressLayer string   `json:"ingressAddressLayer,omitempty"`
	IngressNodes        []string `json:"ingressNodes,omitempty"`

	// IngressNodeLabel is the label the host-bind front-door component selects on, and
	// the label Apply applies to IngressNodes before committing the overlay. Empty
	// means DefaultIngressNodeLabel. Recorded in the plan so the label that gets
	// applied and the label the rendered component selects cannot drift apart.
	IngressNodeLabel string `json:"ingressNodeLabel,omitempty"`

	// IngressHostCIDR is the prefix the platform NetworkPolicies must admit so the
	// host-bound Envoy — which reaches upstreams with a NODE address — is not denied.
	// Derived from the ingress nodes' InternalIPs during Apply (see ingresscidr.go),
	// never from the discovered NODE_CIDR, which on real clusters can be a different
	// network entirely.
	//
	// Deliberately NOT part of the plan HASH: it is read from the live cluster rather
	// than supplied by the operator, so hashing it would make an approved plan stop
	// matching whenever a node's address changed.
	IngressHostCIDR string `json:"ingressHostCIDR,omitempty"`
	// FrontDoor is the one-line plain-words summary printed in the reviewed
	// inputs. It is ALWAYS present, because "which address do my users dial"
	// is the question operators most often discover the answer to after the
	// install rather than during the review.
	FrontDoor            string `json:"frontDoor,omitempty"`
	TrustedCAFingerprint string `json:"trustedCaFingerprint,omitempty"`
	Preset               Preset `json:"preset"`
	Mode                 Mode   `json:"mode"`

	// --- Detected from the fleet state ---
	// PriorClusters lists sibling cluster names when fleet-mode is
	// existing-fleet, used by the "Detected: existing-fleet" header.
	// Empty for new-repo / fresh installs.
	PriorClusters []string `json:"priorClusters,omitempty"`

	// InheritedDefaults are version pins (KUBE_DC_PLATFORM_VERSION,
	// chart versions, etc.) inherited from sibling clusters in
	// existing-fleet mode (M4-T13). Empty for greenfield installs.
	InheritedDefaults map[string]string `json:"inheritedDefaults,omitempty"`
	// InheritanceTemplate is the sibling cluster name whose values
	// won when siblings disagreed on a version pin (M4-T13's
	// "most-recently-modified template" rule). Surfaced in the
	// plan header so operators see which sibling drove the picks.
	InheritanceTemplate string `json:"inheritanceTemplate,omitempty"`

	// --- Action lists ---
	FilesToWrite          []PlanFile         `json:"filesToWrite"`
	ScriptsToRun          []ScriptInvocation `json:"scriptsToRun"`
	ClusterMutations      []Mutation         `json:"clusterMutations"`
	ConfirmationsRequired []Confirmation     `json:"confirmationsRequired"`
	SkippedExistingFleet  []string           `json:"skippedExistingFleet,omitempty"`

	// Warnings are non-gating consequences the operator has already
	// consented to by their explicit flag choices, but that the plan
	// MUST still state honestly (OS-1: --object-storage-mode=disabled
	// → platform monitoring will not converge). Rendered prominently
	// before the file list; part of the hashed plan so a reviewed
	// warning can't silently vanish between dry-run and apply.
	Warnings []string `json:"warnings,omitempty"`
}

// PlanFile is one line in the "Files to write" preview. Path is
// relative to the fleet repo root; Description is the human label.
type PlanFile struct {
	Path        string `json:"path"`
	Description string `json:"description"`
	// Action is `+` (create), `~` (modify), or `-` (delete) — matches
	// the §5.3 text preview's left-column marker.
	Action string `json:"action"`
}

// ScriptInvocation describes one entry in the "Scripts to run"
// section. Index is 1-based execution order; DeferredUntil names a
// runtime gate when non-empty (e.g. "HelmRelease/openbao Ready").
type ScriptInvocation struct {
	Index         int               `json:"index"`
	Kind          string            `json:"kind"` // ports.ScriptKind string, or "(in-process)" for non-script steps
	Args          []string          `json:"args,omitempty"`
	Env           map[string]string `json:"env,omitempty"`
	DeferredUntil string            `json:"deferredUntil,omitempty"`
	Note          string            `json:"note,omitempty"`
}

// Mutation is one expected cluster-side change. Used by Render to
// produce the "Cluster mutations" block.
type Mutation struct {
	Kind      string `json:"kind"`
	Namespace string `json:"namespace,omitempty"`
	Name      string `json:"name"`
	Note      string `json:"note,omitempty"`
}

// Confirmation is one interactive prompt that the apply path needs to
// surface (TTY mode). `--yes` bypasses all of these.
type Confirmation struct {
	ID      string `json:"id"`
	Prompt  string `json:"prompt"`
	Default bool   `json:"default"`
}

// --- Errors ---

// ErrPlanInputDrift fires when --apply-plan recomputes InputHash from
// current InitOptions and gets a different value than the plan
// captured. The operator edited something between dry-run and apply.
var ErrPlanInputDrift = errors.New("init: applied plan inputs drifted from current --set / --node-nic / etc.")

// **Apply-plan verbatim contract** (M4-T04+T09+T13 review-pass — P2):
//
// The apply path (`--apply-plan <path>`) MUST consume the loaded
// `Plan` directly and MUST NOT re-derive fleet-state values
// (InheritedDefaults, PriorClusters, InheritanceTemplate) by
// re-calling `discoverFleetState` or `InheritFromSiblings` against
// the current repo. Sibling clusters can change between the
// operator's dry-run and apply (a coworker bumps `cloud`'s
// KUBE_DC_VERSION); re-deriving would silently change what gets
// written to the new cluster's cluster-config.env vs what the
// operator reviewed.
//
// What this means in practice for M4-T10..T12 engine slices:
//
//   - The engine takes a `*Plan` as input (NOT an
//     `*InitOptions` + a fresh `discoverFleetState` call).
//   - For `--apply-plan`, the cobra layer calls `LoadPlan` once
//     then hands the loaded Plan to the engine.
//   - For `--dry-run`+immediate-apply (`--yes` without
//     `--apply-plan`), the cobra layer calls `BuildPlan` once and
//     reuses that result; the engine still consumes the resulting
//     `*Plan`, not a freshly-discovered FleetState.
//
// `InputHash` covers the operator-supplied options (catches
// "I edited cluster-config.env between dry-run and apply").
// The verbatim contract above is what catches "a sibling changed
// underneath me" — by structural code shape rather than by
// recomputing a fleet-state hash, which would invalidate apply-
// plan on unrelated sibling tweaks.

// ErrPlanHashMismatch fires when LoadPlan recomputes PlanHash from the
// on-disk bytes and gets a different value than the plan claims.
// Indicates a corrupt or tampered plan file.
var ErrPlanHashMismatch = errors.New("init: plan file PlanHash doesn't match its content")

// ErrPlanSchemaVersion fires when LoadPlan reads a Version field that
// doesn't match PlanSchemaVersion. The user must re-dry-run with the
// current CLI to regenerate.
var ErrPlanSchemaVersion = errors.New("init: plan file schema version doesn't match the current CLI")

// ErrNoConsent fires when --no-tty is set without any of:
//   - --yes
//   - --apply-plan <path>
//   - a matching consent-cache marker from a prior --dry-run
//
// The cobra layer surfaces this with a help block listing the three
// options. Distinct from ErrApplyGate (the structural cobra check) —
// ErrNoConsent is engine-time, after consent-cache lookup.
var ErrNoConsent = errors.New("init: --no-tty without --yes / --apply-plan / matching --dry-run consent")

// --- Hashing + canonical JSON ---

// canonicalJSON marshals v to its determined canonical-JSON form:
// sorted keys (encoding/json does this for maps; struct field order is
// preserved which is fine because struct definitions don't change at
// runtime), no trailing newline, no escape-html. Used by both
// ComputeInputHash and the Plan.computeHash internal flow.
// frontDoorPlan resolves the front door for the plan header: the layer that
// will actually be built plus a plain-words summary naming the ADDRESS users
// will dial and the nodes that will answer. The summary is deliberately
// concrete — an operator reviewing "metallb-l2" learns nothing they did not
// already type, but "VIP 192.0.2.10, announced by ARP from 2 ingress node(s)"
// is checkable against the network they were given.
func frontDoorPlan(o *InitOptions) (layer, summary string) {
	// An env-resolution failure means the preset itself is broken, which
	// validation reports far more precisely than a summary line could. Fall
	// back to the raw --set values so the summary degrades instead of lying.
	env, err := ResolvedEnvFor(o)
	if err != nil {
		env = o.Sets
	}
	layer, ambiguous := resolveAddressLayer(o.IngressAddressLayer,
		env["METALLB_FLOATING_IP"], env["METALLB_MODE"])
	vip := strings.TrimSpace(env["METALLB_FLOATING_IP"])
	// The DERIVED set, not the raw flag: an operator who named no ingress
	// nodes still gets the gateway nodes, and the plan should name them —
	// "which machines will answer :443" is not a question to leave implicit.
	nodes, fromGateway := ResolveIngressNodes(o, env)
	// Deliberately NOT the node list: the "ingress nodes:" clause appended
	// below already names them, and saying it twice made the line harder to
	// read than saying it once.
	where := "the ingress nodes' own addresses"
	switch {
	case ambiguous:
		// Validation refuses this, so it can only be seen with validation
		// bypassed. Say so rather than printing a confident "none".
		summary = fmt.Sprintf("UNRESOLVED — %s is reserved but no address layer claims it; pass --ingress-address-layer", vip)
	case layer == AddressLayerMetalLBL2:
		summary = fmt.Sprintf("MetalLB L2 — VIP %s, announced by ARP/GARP from whichever ingress node holds it", vip)
	case layer == AddressLayerMetalLBBGP:
		summary = fmt.Sprintf("MetalLB BGP — VIP %s, announced as a /32 to the peer", vip)
	default:
		summary = fmt.Sprintf("direct — no VIP; clients reach %s (point DNS at them)", where)
	}
	switch {
	case len(nodes) > 0 && fromGateway:
		summary += fmt.Sprintf(" | ingress nodes: %s (derived from KUBE_OVN_GW_NODES)", strings.Join(nodes, ", "))
	case len(nodes) > 0:
		summary += fmt.Sprintf(" | ingress nodes: %s", strings.Join(nodes, ", "))
	default:
		summary += " | ingress nodes: NOT DECLARED and no gateway nodes to derive from"
	}
	return layer, summary
}

// resolvedIngressNodesFor is frontDoorPlan's node half, split out so the plan
// header can carry the same set the summary names.
// resolvedLayerForPlan resolves the address layer exactly the way the plan
// summary and the addons writer do, so the file list, the "Front door:" line
// and what Apply actually writes can never disagree about MetalLB.
func resolvedLayerForPlan(o *InitOptions) string {
	env, err := ResolvedEnvFor(o)
	if err != nil {
		env = o.Sets
	}
	layer, _ := resolveAddressLayer(o.IngressAddressLayer,
		env["METALLB_FLOATING_IP"], env["METALLB_MODE"])
	return layer
}

func resolvedIngressNodesFor(o *InitOptions) ([]string, bool) {
	env, err := ResolvedEnvFor(o)
	if err != nil {
		env = o.Sets
	}
	return ResolveIngressNodes(o, env)
}

// canonicalIngressNodes sorts + de-duplicates the ingress-node set so the
// plan hash depends on WHICH nodes were chosen, never on the order the
// operator typed them.
func canonicalIngressNodes(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	seen := make(map[string]bool, len(in))
	out := make([]string, 0, len(in))
	for _, n := range in {
		n = strings.TrimSpace(n)
		if n == "" || seen[n] {
			continue
		}
		seen[n] = true
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

func canonicalJSON(v any) ([]byte, error) {
	// json.Marshal already sorts map keys but applies HTML escaping
	// by default; switch to Encoder so we can disable it (HTML escapes
	// are not stable across encoder versions and would silently break
	// hash equality if a default flipped).
	var buf strings.Builder
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	out := []byte(strings.TrimRight(buf.String(), "\n"))
	return out, nil
}

// hashHex returns the lowercase-hex SHA-256 of `data`. Kept as a
// helper so the hash algorithm can be changed in one place (a future
// schema bump might want a different hash).
func hashHex(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// inputsForHash is the projection of InitOptions that participates in
// InputHash. Two categories of fields are deliberately excluded:
//
//  1. **Apply-flow flags** — DryRun, ApplyPlan, PlanFile, Yes, NoTTY,
//     NoPush differ between dry-run and apply runs by design (operator
//     runs --dry-run, then --apply-plan with --yes), so including them
//     would make every apply-plan fail with ErrPlanInputDrift.
//
//  2. **Execution-time credentials** — GitHubToken (M4-T01+T02
//     review-pass — P2). A token is auth material, not a *substantive*
//     plan input; what the plan does doesn't depend on which token is
//     used. Including it means rotating tokens or switching between
//     --github-token=... and the `gh auth token` resolution path would
//     break --apply-plan even when the plan is otherwise identical.
//     It's also poor secret hygiene to derive a persisted hash from a
//     credential — the hash is not reversible, but any token-derived
//     artefact is best avoided. The cobra layer still validates token
//     availability at apply time, just not via the plan hash.
//
// Everything else — the substantive inputs that determine what the
// plan does — is included.
//
// Field order is fixed (struct field order = encoding/json key order)
// so the hash is deterministic. Adding a new substantive field to
// InitOptions means adding it here too; the
// TestComputeInputHash_SensitiveToChange table guards the
// "meaningful field changes the hash" invariant.
type inputsForHash struct {
	Preset         Preset            `json:"preset"`
	Mode           Mode              `json:"mode"`
	Name           string            `json:"name"`
	Domain         string            `json:"domain"`
	NodeExternalIP string            `json:"nodeExternalIp"`
	Email          string            `json:"email"`
	FleetMode      FleetMode         `json:"fleetMode"`
	Repo           string            `json:"repo"`
	Provider       Provider          `json:"provider,omitempty"`
	GitHubOwner    string            `json:"githubOwner"`
	GitHubRepo     string            `json:"githubRepo"`
	Sets           map[string]string `json:"sets,omitempty"`
	NodeNICs       map[string]string `json:"nodeNics,omitempty"`
	RookMode       RookMode          `json:"rookMode"`
	RookOSDNode    string            `json:"rookOsdNode"`
	RookOSDSizeGB  int               `json:"rookOsdSizeGb"`
	// OS-1 object-storage companions — all substantive: a mode or
	// companion change between dry-run and apply MUST drift-detect
	// (they select which fleet manifests get scaffolded + which
	// CEPH_*/S3_* env keys land in cluster-config.env).
	RookOSDDevice       string            `json:"rookOsdDevice"`
	CephNodes           map[string]string `json:"cephNodes,omitempty"`
	CephStorageClass    string            `json:"cephStorageClass"`
	CephOSDCount        int               `json:"cephOsdCount"`
	CephOSDVolumeSizeGB int               `json:"cephOsdVolumeSizeGb"`
	S3Hostname          string            `json:"s3Hostname"`
	NoS3Exposure        bool              `json:"noS3Exposure"`
	// VM root-disk storage — substantive: the mode + golden subset select
	// which rbd-vm fleet manifests get scaffolded (vmstorage.go). Dry-run
	// + apply MUST agree or an operator could preview a shared-rbd plan and
	// apply a local-only one (or a different golden subset).
	VMStorageMode VMStorageMode `json:"vmStorageMode"`
	// TLSMode is substantive: byo-wildcard scaffolds the SOPS secret set +
	// ACME suppression patches; acme scaffolds nothing. Canonicalized so the
	// default ("" == acme) is OMITTED — a plan hashed by an older CLI stays
	// byte-identical, and `--tls-mode acme` spelled explicitly hashes the
	// same as not passing the flag. The cert/key PATHS are deliberately NOT
	// in the plan: they are machine-local inputs, and the material itself is
	// data (the SOPS artifact), not shape.
	// Front door (design v2 §5a): the address layer changes the Envoy Service
	// shape the fleet renders and the ingress-node set changes which hosts
	// bind :80/:443 — both are scaffold shape, so both are hashed. Nodes are
	// sorted so flag order cannot change the hash.
	IngressAddressLayer string   `json:"ingressAddressLayer,omitempty"`
	IngressNodes        []string `json:"ingressNodes,omitempty"`
	TLSMode             string   `json:"tlsMode,omitempty"`
	// TLSCertFingerprint (hex SHA-256 of the leaf DER — public material) binds
	// the plan to the CERTIFICATE the operator reviewed, not merely the mode:
	// apply refuses material whose fingerprint differs from the approved plan.
	TLSCertFingerprint string `json:"tlsCertFingerprint,omitempty"`
	// The dns01 solver config is shape (it changes the ClusterIssuer patch
	// and the SOPS artifact identity), so all four participate in the hash.
	DNS01Route53ZoneID        string                 `json:"dns01Route53ZoneId,omitempty"`
	DNS01Route53Region        string                 `json:"dns01Route53Region,omitempty"`
	DNS01Route53AccessKeyID   string                 `json:"dns01Route53AccessKeyId,omitempty"`
	DNS01SecretKeyFingerprint string                 `json:"dns01SecretKeyFingerprint,omitempty"`
	TrustedCAFingerprint      string                 `json:"trustedCaFingerprint,omitempty"`
	ImageAcceleration         bool                   `json:"imageAcceleration,omitempty"`
	VMGoldens                 []string               `json:"vmGoldens,omitempty"`
	VMGoldensBlock            []string               `json:"vmGoldensBlock,omitempty"`
	GPUPlatform               GPUPlatformMode        `json:"gpuPlatform,omitempty"`
	GPUDriverSource           GPUDriverSource        `json:"gpuDriverSource,omitempty"`
	GPUOperatorVersion        string                 `json:"gpuOperatorVersion,omitempty"`
	NVIDIADriverVersion       string                 `json:"nvidiaDriverVersion,omitempty"`
	NVIDIAToolkitVersion      string                 `json:"nvidiaToolkitVersion,omitempty"`
	HAMiEnabled               bool                   `json:"hamiEnabled,omitempty"`
	GPUSharedAllocator        GPUSharedAllocator     `json:"gpuSharedAllocator,omitempty"`
	HAMiVersion               string                 `json:"hamiVersion,omitempty"`
	HAMiSchedulerVersion      string                 `json:"hamiSchedulerVersion,omitempty"`
	GPUNodeModes              map[string]GPUNodeMode `json:"gpuNodeModes,omitempty"`
	GPUProfiles               []string               `json:"gpuProfiles,omitempty"`
	AllowUnassignedGPUs       bool                   `json:"allowUnassignedGpus,omitempty"`
	VGPUSecretReady           bool                   `json:"vgpuSecretReady,omitempty"`
	Addons                    []string               `json:"addons,omitempty"`
	AllowDNSNotReady          bool                   `json:"allowDnsNotReady"`
	AllowNoKubevirtEligible   bool                   `json:"allowNoKubevirtEligible"`
	// AllowUnpinnedAdopt IS substantive (like its Allow* siblings): it
	// changes whether the --mode=adopt safety gate blocks or merely
	// warns. Dry-run + apply MUST agree, or an operator could review a
	// plan that would refuse an unpinned cluster and then apply with the
	// bypass set.
	AllowUnpinnedAdopt bool `json:"allowUnpinnedAdopt"`
	// NoPush IS substantive — it changes apply-time behavior
	// (skips `git push` + `flux-install.sh` — the cluster overlay
	// stays local-only). Dry-run + apply MUST agree on this flag
	// or an operator can review a local-only preview and
	// accidentally apply a real commit+push+flux-install run (or
	// vice versa). C4 reviewer P1 catch on 48d57b8f.
	NoPush           bool   `json:"noPush"`
	SSHHost          string `json:"sshHost"`
	NoSSH            bool   `json:"noSsh"`
	NoInstallPrereqs bool   `json:"noInstallPrereqs"`
	NoCreateRepo     bool   `json:"noCreateRepo"`
	StarterRef       string `json:"starterRef"`
	MirrorRegistry   string `json:"mirrorRegistry"`
	BundlePullSecret string `json:"bundlePullSecret"`
	OpenBaoSharesOut string `json:"openbaoSharesOut"`
}

// hashExcludedFields is the registry of `InitOptions` fields that
// are DELIBERATELY not part of the plan input hash. These fall
// into two buckets:
//
//   - Apply-flow flags that SHOULD differ between dry-run and
//     `--apply-plan` runs (an operator dry-runs, reviews the plan,
//     then applies without `--dry-run`; the plan hash MUST
//     collapse those two invocations to the same value).
//   - Secrets / env-derived / transient fields not committed to
//     the on-disk plan.
//
// **Contract** (enforced by `TestPlanHashCoverage_AllInitOptionsFieldsAccountedFor`,
// aka C4 re-entrance lint): every field on `InitOptions` MUST
// appear either here OR in `inputsForHash` — never both. Adding a
// new field means picking a bucket at introduction time; the
// choice becomes reviewer-visible via the required entry here.
//
// The map's value is the per-field rationale — kept next to the
// key so a grep for a field name lands on the "why" immediately.
var hashExcludedFields = map[string]string{
	// Apply-flow flags — MUST differ between dry-run + --apply-plan.
	// NOTE: `NoPush` is NOT in this bucket even though it looks
	// flag-shaped — it changes apply-time behavior (skips push +
	// flux-install), so dry-run and apply MUST agree on it or an
	// operator can review a local-only preview and accidentally
	// commit-push-flux to production. It lives in `inputsForHash`.
	"DryRun":    "apply-flow flag: dry-run → apply must not trigger plan-hash drift",
	"ApplyPlan": "apply-flow flag: path to a prior plan file, per-invocation",
	"PlanFile":  "apply-flow flag: path to write plan.json, per-invocation",
	"NoTTY":     "apply-flow flag: output formatting only, no semantic effect",
	"Yes":       "apply-flow flag: consent for automation (CI); no semantic effect",

	// Secrets / env — deliberately excluded from the on-disk plan.
	"GitHubToken": "secret material; MUST never touch the plan file even in-memory",
	// TLSMode IS hashed (it changes what the scaffold writes). The paths are
	// machine-local pointers to the material, and the material itself is
	// secret DATA, not scaffold shape: it must never ride the plan file, and
	// hashing the paths would break apply-plan from a different machine or
	// directory while proving nothing (the same path can hold different
	// bytes). LoadWildcardTLS re-validates the actual material at BOTH
	// dry-run and apply, which is the real drift guard.
	"TLSCert":                   "machine-local path to secret material; validated at load, never planned",
	"TLSKey":                    "machine-local path to secret material; validated at load, never planned",
	"DNS01Route53SecretKeyFile": "machine-local path to secret material; fingerprint is hashed instead",
	"TrustedCABundle":           "machine-local path to public CA material; canonical bundle fingerprint is hashed instead",

	// Transient OUTPUT — filled by the post-apply phase (end-of-install
	// access block); never an input to the plan.
	"AccessSummary": "transient output (end-of-install access block); not a plan input",
	"PrefillNotes":  "transient output (legacy-key translation notices); not a plan input",
	// DISCOVERED from the live cluster, not operator input: hashing it would make
	// the plan hash depend on which nodes happened to answer, so an unrelated
	// node roll would read as plan drift.
	"ControlPlaneNodes": "discovered from the live cluster; not an operator input",
}

// normalizeProviderForHash collapses explicit `github` to the
// default empty form so the input hash treats them as equivalent.
// GitLab surfaces verbatim (non-default → must participate in
// the hash so gitlab-plan / github-apply drift IS caught).
func normalizeProviderForHash(p Provider) Provider {
	if p == ProviderGitHub {
		return ""
	}
	return p
}

func (o *InitOptions) inputsForHash() inputsForHash {
	return inputsForHash{
		Preset:         o.Preset,
		Mode:           o.Mode,
		Name:           o.Name,
		Domain:         o.Domain,
		NodeExternalIP: o.NodeExternalIP,
		Email:          o.Email,
		FleetMode:      o.FleetMode,
		Repo:           o.Repo,
		// P3: normalize explicit `github` → empty so the default
		// (empty) and the explicit form hash IDENTICALLY. Without
		// this, an operator who dry-runs against the implicit
		// default and then passes --provider=github at apply time
		// (or vice versa) would trip ErrPlanInputDrift with no
		// semantic change. Only non-default providers surface in
		// the hash. Combined with `json:"provider,omitempty"` the
		// canonical JSON omits the field for the default case.
		Provider:            normalizeProviderForHash(o.Provider),
		GitHubOwner:         o.GitHubOwner,
		GitHubRepo:          o.GitHubRepo,
		Sets:                o.Sets,
		NodeNICs:            o.NodeNICs,
		RookMode:            o.RookMode,
		RookOSDNode:         o.RookOSDNode,
		RookOSDSizeGB:       o.RookOSDSizeGB,
		RookOSDDevice:       o.RookOSDDevice,
		CephNodes:           o.CephNodes,
		CephStorageClass:    o.CephStorageClass,
		CephOSDCount:        o.CephOSDCount,
		CephOSDVolumeSizeGB: o.CephOSDVolumeSizeGB,
		S3Hostname:          o.S3Hostname,
		NoS3Exposure:        o.NoS3Exposure,
		VMStorageMode:       o.VMStorageMode,
		ImageAcceleration:   o.ImageAcceleration,
		// The EXPLICIT flag, never the resolved layer. Hashing the resolved
		// value would turn an absent flag into "none" and change the hash of
		// every plan written by an older CLI — a spurious drift error in the
		// middle of somebody's install. The resolved layer belongs on the
		// plan HEADER (what will be built); the hash covers what was SAID.
		IngressAddressLayer:       o.IngressAddressLayer,
		IngressNodes:              canonicalIngressNodes(o.IngressNodes),
		TLSMode:                   canonicalTLSMode(o.TLSMode),
		TLSCertFingerprint:        o.TLSCertFingerprint,
		DNS01Route53ZoneID:        o.DNS01Route53ZoneID,
		DNS01Route53Region:        o.DNS01Route53Region,
		DNS01Route53AccessKeyID:   o.DNS01Route53AccessKeyID,
		DNS01SecretKeyFingerprint: o.DNS01SecretKeyFingerprint,
		TrustedCAFingerprint:      o.TrustedCAFingerprint,
		VMGoldens:                 canonicalGoldens(o.VMGoldens),
		VMGoldensBlock:            canonicalGoldens(o.VMGoldensBlock),
		GPUPlatform:               o.GPUPlatform,
		GPUDriverSource:           o.GPUDriverSource,
		GPUOperatorVersion:        o.GPUOperatorVersion,
		NVIDIADriverVersion:       o.NVIDIADriverVersion,
		NVIDIAToolkitVersion:      o.NVIDIAToolkitVersion,
		HAMiEnabled:               o.HAMiEnabled,
		GPUSharedAllocator:        o.GPUSharedAllocator,
		HAMiVersion:               o.HAMiVersion,
		HAMiSchedulerVersion:      o.HAMiSchedulerVersion,
		GPUNodeModes:              o.GPUNodeModes,
		GPUProfiles:               canonicalGPUProfiles(o.GPUProfiles),
		AllowUnassignedGPUs:       o.AllowUnassignedGPUs,
		VGPUSecretReady:           o.VGPUSecretReady,
		Addons:                    o.Addons,
		AllowDNSNotReady:          o.AllowDNSNotReady,
		AllowNoKubevirtEligible:   o.AllowNoKubevirtEligible,
		AllowUnpinnedAdopt:        o.AllowUnpinnedAdopt,
		NoPush:                    o.NoPush,
		SSHHost:                   o.SSHHost,
		NoSSH:                     o.NoSSH,
		NoInstallPrereqs:          o.NoInstallPrereqs,
		NoCreateRepo:              o.NoCreateRepo,
		StarterRef:                o.StarterRef,
		MirrorRegistry:            o.MirrorRegistry,
		BundlePullSecret:          o.BundlePullSecret,
		OpenBaoSharesOut:          o.OpenBaoSharesOut,
	}
}

// ComputeInputHash returns the SHA-256 of canonical-JSON of the
// **substantive** subset of `o` — see `inputsForHash` doc for the
// exclusion list (apply-flow flags + execution-time credentials).
// Stable across runs + platforms.
func ComputeInputHash(o *InitOptions) (string, error) {
	if o == nil {
		return "", fmt.Errorf("ComputeInputHash: nil options")
	}
	data, err := canonicalJSON(o.inputsForHash())
	if err != nil {
		return "", fmt.Errorf("canonical-JSON options: %w", err)
	}
	return hashHex(data), nil
}

// computeHash returns the SHA-256 of `p` with the metadata-only
// fields zeroed (`PlanHash` and `GeneratedAt`). Used internally by
// BuildPlan (to set PlanHash) and by LoadPlan (to verify the
// on-disk value).
//
// **Why GeneratedAt is zeroed** (M4-T01+T02 review-pass — P1): the
// Plan type doc declares "GeneratedAt is NOT hashed; it's metadata."
// Earlier `computeHash` only zeroed `PlanHash`, so two BuildPlans
// from the same inputs at different seconds produced different
// PlanHash values — a silent determinism bug that undermined the
// hash-pinning safety contract. Zeroing here restores the
// documented invariant; `TestPlan_PlanHashExcludesGeneratedAt`
// guards against regression by forcing two plans with different
// `GeneratedAt` values and asserting identical PlanHash.
func (p *Plan) computeHash() (string, error) {
	clone := *p
	clone.PlanHash = ""
	clone.GeneratedAt = time.Time{}
	data, err := canonicalJSON(&clone)
	if err != nil {
		return "", fmt.Errorf("canonical-JSON plan: %w", err)
	}
	return hashHex(data), nil
}

// --- BuildPlan ---

// FleetState is the subset of "what the fleet repo looks like right
// now" that plan generation needs. The cobra layer populates this
// from `discover.ListClusters` + `clusterinit.InheritFromSiblings`
// (M4-T13); tests build it directly with hand-crafted siblings.
type FleetState struct {
	// PriorClusters lists existing `clusters/<name>/` overlays.
	// Empty for new-repo greenfield installs.
	PriorClusters []string
	// SOPSRecipients is the count of `.sops.yaml` recipients in
	// existing-fleet mode; the plan-render uses this for the "12
	// keys; encrypted to N recipients" line.
	SOPSRecipients int
	// PlatformVersion is the legacy single-version pin previously
	// surfaced in the plan header. Kept for one release as a
	// fallback when `InheritedDefaults` doesn't carry
	// KUBE_DC_PLATFORM_VERSION; new callers should pass siblings +
	// rely on InheritedDefaults instead.
	//
	// Deprecated: populate `Siblings` and let BuildPlan derive
	// inheritance from them.
	PlatformVersion string

	// Siblings is the full sibling-cluster list with parsed envs +
	// ModTimes. M4-T13's `InheritFromSiblings` consumes this to
	// derive the version-pin defaults; the cobra layer fills it
	// from disk before BuildPlan runs.
	Siblings []SiblingCluster
	// InheritedDefaults is the merged version-pin map from
	// InheritFromSiblings — pre-computed so BuildPlan doesn't have
	// to walk Siblings again. Empty for greenfield / new-repo.
	InheritedDefaults map[string]string
	// InheritanceTemplate is the sibling whose values won when
	// siblings disagreed (from InheritanceResult.TemplateName).
	// Rendered in the "Detected: existing-fleet → using <name>"
	// header line.
	InheritanceTemplate string
}

// BuildPlan derives the deterministic Plan from validated options +
// fleet state. Sorts everything order-irrelevant; preserves
// execution-order slices verbatim; fills both hashes.
//
// **Scope of T02**: the file/script enumeration is the
// canonical-§5.3/§5.5 skeleton. T04 (presets), T10 (scaffold), T11
// (customInterfaces), T12 (commit/push/flux), T13 (existing-fleet
// inheritance) will replace these placeholders with engine-derived
// values. Operators dry-running today see what they'll see at first
// apply once those slices ship — only the "exact line count" preview
// values are placeholders.
func BuildPlan(o *InitOptions, fleet FleetState) (*Plan, error) {
	planLayer, planFrontDoor := frontDoorPlan(o)
	// The RESOLVED set, so the header and the human summary agree and scaffold
	// consumes the nodes the operator actually reviewed. Storing the raw list
	// here while printing the derived one meant the :6443 derivation ran on a
	// different set than the plan showed.
	planIngressNodes, _ := resolvedIngressNodesFor(o)
	if o == nil {
		return nil, fmt.Errorf("BuildPlan: nil options")
	}
	if err := o.Validate(); err != nil {
		return nil, fmt.Errorf("BuildPlan: %w", err)
	}

	inputHash, err := ComputeInputHash(o)
	if err != nil {
		return nil, err
	}

	p := &Plan{
		Version:             PlanSchemaVersion,
		InputHash:           inputHash,
		GeneratedAt:         time.Now().UTC().Truncate(time.Second),
		ClusterName:         o.Name,
		Domain:              o.Domain,
		FleetMode:           o.FleetMode,
		StarterRef:          o.StarterRef,
		OpenBaoSharesOut:    o.OpenBaoSharesOut,
		Preset:              o.Preset,
		Mode:                o.Mode,
		IngressAddressLayer: planLayer,
		IngressNodes:        planIngressNodes,
		// The label Apply will put on those nodes, recorded next to the resolved node
		// set so the label that gets APPLIED and the label the rendered host-bind
		// component SELECTS cannot drift apart. Empty means DefaultIngressNodeLabel.
		IngressNodeLabel:          DefaultIngressNodeLabel,
		FrontDoor:                 planFrontDoor,
		TLSMode:                   canonicalTLSMode(o.TLSMode),
		TLSCertFingerprint:        o.TLSCertFingerprint,
		DNS01SecretKeyFingerprint: o.DNS01SecretKeyFingerprint,
		TrustedCAFingerprint:      o.TrustedCAFingerprint,
	}

	if o.FleetMode == FleetExistingFleet {
		sorted := append([]string(nil), fleet.PriorClusters...)
		sort.Strings(sorted)
		p.PriorClusters = sorted
		// M4-T13 + review-pass P3: defensive-copy the
		// InheritedDefaults map so a caller mutating
		// `fleet.InheritedDefaults` after BuildPlan returns can't
		// silently corrupt the plan's contents without the
		// PlanHash detecting it (since the hash was computed
		// before the mutation). The plan owns its own copy.
		switch {
		case len(fleet.InheritedDefaults) > 0:
			cp := make(map[string]string, len(fleet.InheritedDefaults))
			for k, v := range fleet.InheritedDefaults {
				cp[k] = v
			}
			p.InheritedDefaults = cp
		case fleet.PlatformVersion != "":
			p.InheritedDefaults = map[string]string{
				"KUBE_DC_PLATFORM_VERSION": fleet.PlatformVersion,
			}
		}
		p.InheritanceTemplate = fleet.InheritanceTemplate
	}

	p.FilesToWrite = filesForOptions(o, fleet)
	p.ScriptsToRun = scriptsForOptions(o, fleet)
	p.ClusterMutations = mutationsForOptions(o)
	p.ConfirmationsRequired = confirmationsForOptions(o)
	p.SkippedExistingFleet = skippedForOptions(o, fleet)
	p.Warnings = warningsForOptions(o)

	hash, err := p.computeHash()
	if err != nil {
		return nil, err
	}
	p.PlanHash = hash
	return p, nil
}

// filesForOptions returns the deterministic "Files to write" list.
// T04 wired the preset's Kustomization list + env-map size into the
// descriptions; T10 will refine further when the actual scaffold
// engine writes the files.
func filesForOptions(o *InitOptions, fleet FleetState) []PlanFile {
	base := o.Name + "/"

	// Derive the cluster-config.env line count from the preset's
	// resolved env map. Operators see "(42 keys)" rather than a
	// generic placeholder — catches "I missed a --set" before
	// scrolling through the deferred T10 file.
	envKeyCount := 0
	if envMap, err := ResolvedEnvFor(o); err == nil {
		envKeyCount = len(envMap)
	}
	envDesc := "cluster-config.env"
	if envKeyCount > 0 {
		envDesc = fmt.Sprintf("cluster-config.env (%d keys, preset=%s)", envKeyCount, o.Preset)
	}
	if n := len(GPUConfigEnv(o.GPU())); n > 0 {
		envDesc += fmt.Sprintf(" + %d GPU contract keys", n)
	}

	// Compose the infrastructure.yaml description from the preset's
	// Kustomization layer set (T04). Atlantis's
	// cloud+public-vlan adds infra-public-network; internal-only
	// omits it. Listing the actual layers makes the dry-run
	// self-documenting for operators reviewing a CI plan.
	infraLayers := infrastructureLayers(o.Preset)
	infraDesc := "infrastructure.yaml"
	if len(infraLayers) > 0 {
		infraDesc = fmt.Sprintf("infrastructure.yaml (%s)", strings.Join(infraLayers, " + "))
	}

	// This MUST mirror exactly what the apply path writes into
	// clusters/<name>/ — add-cluster.sh's six files plus (for rook-*
	// modes) the OS-2 object-storage wiring. The dry-run's value is
	// "review what apply will do", so a prediction that lists files
	// apply won't create (or omits ones it will) breaks trust (E2E
	// shakedown 2026-07-04 caught exactly that drift).
	//
	// add-cluster.sh writes: cluster-config.env, secrets.enc.yaml,
	// patches/versions.yaml, infrastructure.yaml, platform.yaml,
	// kustomization.yaml. The OS-2 writer (objectstorage.go, Scaffold
	// step 7) then adds object-storage/kustomization.yaml +
	// infra-object-storage.yaml and patches platform.yaml (dependsOn)
	// + kustomization.yaml (resources) + cluster-config.env (CEPH_*/
	// S3_* keys) in place — the patched files stay single "+" entries
	// with descriptions covering their final state.
	platformDesc := "platform Kustomization"
	kustDesc := "kustomization.yaml (Flux entry)"
	scaffoldOS := scaffoldsObjectStorage(o.RookMode)
	switch {
	case scaffoldOS:
		platformDesc = "platform Kustomization (dependsOn: infra-core + infra-object-storage)"
		kustDesc = "kustomization.yaml (Flux entry incl. infra-object-storage.yaml)"
		envKeys := objectStorageEnvKeys(o.Domain, o.ObjectStorage())
		envDesc += fmt.Sprintf(" + %d object-storage keys", len(envKeys))
	case o.RookMode == RookDisabled:
		// OS-4 degraded wiring: the suspend key + the grafana-pg
		// backup-path patches land in the same two files.
		platformDesc = "platform Kustomization (patches: grafana-pg backup path removed — degraded mode)"
		envDesc += " + OBJECT_STORAGE_DISABLED=true"
	}
	// VM-storage (vmstorage.go, Scaffold step 9): shared-rbd adds
	// rbd-vm.yaml + a golden subset overlay and patches kustomization.yaml
	// (resources) in place. local + shared-rbd-live-migration (deferred)
	// scaffold nothing.
	scaffoldVM := scaffoldsVMStorage(o.VMStorageMode) && o.VMStorageMode != VMStorageSharedRBDLiveMigration
	if scaffoldVM {
		kustDesc += " incl. rbd-vm.yaml"
	}
	scaffoldGPU := o.GPUPlatform == GPUPlatformEnabled
	if scaffoldGPU {
		kustDesc += " incl. gpu.yaml"
	}
	files := []PlanFile{
		{Path: "clusters/" + base + "cluster-config.env", Description: envDesc, Action: "+"},
		{Path: "clusters/" + base + "secrets.enc.yaml", Description: "secrets.enc.yaml (SOPS-encrypted)", Action: "+"},
		{Path: "clusters/" + base + "patches/versions.yaml", Description: "patches/versions.yaml (version pins)", Action: "+"},
		{Path: "clusters/" + base + "infrastructure.yaml", Description: infraDesc, Action: "+"},
		{Path: "clusters/" + base + "platform.yaml", Description: platformDesc, Action: "+"},
		{Path: "clusters/" + base + "kustomization.yaml", Description: kustDesc, Action: "+"},
		// Tenant Networking v2 — the shared infra Subnet and its Flux
		// Kustomization. This list MUST mirror what the apply path writes; it
		// drifted once already when the scaffold gained these three files.
		{Path: "clusters/" + base + "tenant-net-v2.yaml", Description: "tenant-net-v2 Kustomization (dependsOn infra-cni, prune:false)", Action: "+"},
		{Path: "clusters/" + base + "tenant-net-v2/kustomization.yaml", Description: "tenant-net-v2 kustomization", Action: "+"},
		{Path: "clusters/" + base + "tenant-net-v2/infra-net.yaml", Description: "infra-net Subnet (dual-home eth0)", Action: "+"},
		{Path: "clusters/" + base + "cdi-block-device-access.yaml", Description: "CDI block-device access policy Flux layer", Action: "+"},
		{Path: "clusters/" + base + "ext-net-bridge-tag.yaml", Description: "external bridge, anchor and optional node-egress worker Flux layer", Action: "+"},
	}
	// The MetalLB layers are written ONLY under a VIP layer — addons.go installs
	// nothing for layer=none, whose entire promise is "no MetalLB on sites with
	// no spare address". The plan used to list all four files unconditionally,
	// so a reviewed none plan promised files the apply never writes. A plan is a
	// statement of what will be BUILT; the operator approves what they read.
	if addressLayerRequiresVIP(resolvedLayerForPlan(o)) {
		files = append(files,
			PlanFile{Path: "clusters/" + base + "addons.yaml", Description: "MetalLB operator Flux layer", Action: "+"},
			PlanFile{Path: "clusters/" + base + "addons-config.yaml", Description: "MetalLB resources Flux layer (health-gated after operator)", Action: "+"},
			PlanFile{Path: "clusters/" + base + "addons/kustomization.yaml", Description: "MetalLB operator overlay", Action: "+"},
			PlanFile{Path: "clusters/" + base + "addons-config/kustomization.yaml", Description: "MetalLB L2/BGP configuration overlay", Action: "+"},
		)
	}
	if scaffoldOS {
		layers := "modes/" + string(o.RookMode) + " + bucket-provisioning"
		if !o.NoS3Exposure {
			layers += " + exposure"
		}
		files = append(files,
			PlanFile{Path: "clusters/" + base + "object-storage/kustomization.yaml",
				Description: "object-storage overlay (" + layers + ")", Action: "+"},
			PlanFile{Path: "clusters/" + base + "infra-object-storage.yaml",
				Description: "Flux layer 1d (healthCheck: CephCluster Ready)", Action: "+"},
		)
	}
	if canonicalTLSMode(o.TLSMode) == TLSModeBYOWildcard {
		files = append(files,
			PlanFile{Path: "clusters/" + base + wildcardSecretsFileName,
				Description: "operator wildcard under every platform TLS secret name (SOPS)", Action: "+"},
			PlanFile{Path: "clusters/" + base + "platform.yaml",
				Description: "ACME Certificate suppression patches (byo-wildcard)", Action: "~"},
		)
	}
	if canonicalTLSMode(o.TLSMode) == TLSModeACMEDNS01Route53 {
		files = append(files,
			PlanFile{Path: "clusters/" + base + dns01SecretsFileName,
				Description: "Route53 secret access key for the cert-manager DNS-01 solver (SOPS)", Action: "+"},
			PlanFile{Path: "clusters/" + base + "platform.yaml",
				Description: "ClusterIssuer solver patch → Route53 DNS-01 (acme-dns01-route53)", Action: "~"},
		)
	}
	if o.TrustedCAFingerprint != "" {
		files = append(files, PlanFile{
			Path:        "clusters/" + base + trustedCAFileName,
			Description: "private-CA trust ConfigMap (manager + backend + OIDC + OpenBao; sha256=" + o.TrustedCAFingerprint + ")",
			Action:      "+",
		})
	}
	if o.ImageAcceleration {
		// Image-acceleration trio (imageaccel.go, Scaffold step 9b). Pieces
		// whose platform/ dir is absent from the starter are skipped at
		// apply time with a warning; the S3-backed pieces additionally
		// require an object-storage mode (they depend on
		// infra-object-storage). The plan lists the intent.
		files = append(files,
			PlanFile{Path: "clusters/" + base + "tenant-addons.yaml",
				Description: "tenant-cluster addons (Sveltos: CNI/CoreDNS) Kustomization", Action: "+"},
		)
		if scaffoldsObjectStorage(o.RookMode) {
			files = append(files,
				PlanFile{Path: "platform/registry-depot/secret.enc.yaml",
					Description: "ensure registry-depot push credential exists and is SOPS-encrypted (shared fleet file)", Action: "~"},
				PlanFile{Path: "clusters/" + base + "cdi-os-mirror.yaml",
					Description: "CDI OS-image S3 mirror Kustomization", Action: "+"},
				PlanFile{Path: "clusters/" + base + "registry-depot.yaml",
					Description: "zot registry depot Kustomization (+ minted push credential)", Action: "+"},
			)
		}
	}
	if scaffoldVM {
		goldenDesc := "default (1 golden)"
		if g := canonicalGoldens(o.VMGoldens); len(g) > 0 {
			goldenDesc = strings.Join(g, ",")
		}
		files = append(files,
			PlanFile{Path: "clusters/" + base + "rbd-vm-goldens/kustomization.yaml",
				Description: "rbd-vm FS golden subset (" + goldenDesc + ")", Action: "+"},
			PlanFile{Path: "clusters/" + base + "rbd-vm.yaml",
				Description: "rbd-vm Flux Kustomizations (rbd-vm-base + rbd-vm-goldens)", Action: "+"},
		)
	}
	if scaffoldGPU {
		for _, path := range gpuFiles(o.Name, o.GPU()) {
			if strings.Contains(path, "kustomization.yaml (+ gpu.yaml resource)") {
				continue // represented by the existing kustomization entry above
			}
			desc := "GPU ownership scaffold"
			switch {
			case strings.HasSuffix(path, "nodefeaturerule.yaml"):
				desc = "exact-node GPU ownership rules (nodename + NVIDIA PCI match)"
			case strings.HasSuffix(path, "gpu-node-modes/kustomization.yaml"):
				desc = "GPU node-mode overlay"
			case strings.HasSuffix(path, "gpu.yaml"):
				desc = "GPU Operator + optional HAMi Flux layers (commercial/create gates closed)"
			}
			files = append(files, PlanFile{Path: path, Description: desc, Action: "+"})
		}
	}
	// Stable order — Files-to-Write mirrors the apply write order
	// (add-cluster.sh's six, OS-2 wiring, step-9 VM storage, then step-10 GPU);
	// no need to sort.
	return files
}

// infrastructureLayers returns the Kustomization names that
// `infrastructure.yaml` references for the given preset. The list
// is filtered to the "infra-*" layers only (object-storage /
// platform / addons live in their own files); ordering matches the
// preset spec.
func infrastructureLayers(p Preset) []string {
	all, ok := PresetKustomizations(p)
	if !ok {
		return nil
	}
	var out []string
	for _, k := range all {
		if strings.HasPrefix(k, "infra-") && k != "infra-object-storage" {
			out = append(out, k)
		}
	}
	return out
}

// scriptsForOptions enumerates the run-order steps. Indexes are
// 1-based and assigned monotonically. T10/T12 will refine the actual
// args (e.g. `bootstrap/add-cluster.sh` takes positional args from
// InitOptions); T02 surfaces the canonical step list.
func scriptsForOptions(o *InitOptions, fleet FleetState) []ScriptInvocation {
	scripts := []ScriptInvocation{}
	idx := 0
	add := func(s ScriptInvocation) {
		idx++
		s.Index = idx
		scripts = append(scripts, s)
	}

	// Greenfield-only steps that existing-fleet skips.
	if o.FleetMode != FleetExistingFleet {
		add(ScriptInvocation{Kind: "bootstrap/generate-age-key.sh", Note: "only if age.key missing"})
		add(ScriptInvocation{Kind: "(in-process) extract fleet-starter OCI bundle", Note: "M4-T10"})
	}

	if o.FleetMode != FleetExistingFleet {
		add(ScriptInvocation{
			Kind: "bootstrap/add-cluster.sh",
			Args: []string{o.Name, o.Domain, o.NodeExternalIP},
			Note: "scaffolds clusters/" + o.Name + "/",
		})
	} else {
		add(ScriptInvocation{
			Kind: "(in-process) scaffold from sibling templates",
			Note: "existing-fleet — refuses if clusters/" + o.Name + "/ already exists",
		})
	}

	add(ScriptInvocation{
		Kind: "(in-process) apply form deltas to cluster-config.env",
		Note: "the --set values; preserves key order",
	})
	if len(o.NodeNICs) > 0 {
		add(ScriptInvocation{
			Kind: "(in-process) render customInterfaces into infrastructure.yaml",
			Note: fmt.Sprintf("%d --node-nic mapping(s)", len(o.NodeNICs)),
		})
	}
	if scaffoldsObjectStorage(o.RookMode) {
		// OS-2: mirrors Scaffold step 7 — the writer emits the
		// overlay + Flux layer and patches platform dependsOn +
		// kustomization resources + env keys (see filesForOptions
		// for the resulting file set).
		add(ScriptInvocation{
			Kind: "(in-process) wire object-storage (mode=" + string(o.RookMode) + ")",
			Note: "overlay + infra-object-storage Flux layer + platform dependsOn + CEPH_*/S3_* env keys",
		})
	} else if o.RookMode == RookDisabled {
		// OS-4 degraded wiring.
		add(ScriptInvocation{
			Kind: "(in-process) wire object-storage degraded mode (disabled)",
			Note: "OBJECT_STORAGE_DISABLED=true (suspends Mimir+Loki) + platform.yaml patches removing grafana-pg's backup path",
		})
	}
	if o.GPUPlatform != "" && o.GPUPlatform != GPUPlatformDisabled {
		add(ScriptInvocation{
			Kind: "(in-process) apply accelerator fleet contract",
			Note: fmt.Sprintf("platform=%s; node modes=%s; profiles=%s; secrets remain SOPS-only", o.GPUPlatform, canonicalGPUNodeModes(o.GPUNodeModes), strings.Join(canonicalGPUProfiles(o.GPUProfiles), ",")),
		})
	}
	add(ScriptInvocation{
		Kind: "(in-process) sops encrypt clusters/" + o.Name + "/secrets.enc.yaml",
		Note: sopsRecipientsNote(fleet),
	})
	if o.NoPush {
		// C4 reviewer P1: the render mirrors what apply.go actually
		// runs. With --no-push, apply skips both `git push` and
		// `flux-install.sh` (Flux needs a pushed commit to
		// reconcile) — the operator gets a local commit only, and
		// the plan MUST say so.
		add(ScriptInvocation{
			Kind: "(in-process) git add + commit",
			Note: "--no-push set; push + flux-install skipped (local-only apply)",
		})
	} else {
		add(ScriptInvocation{
			Kind: "(in-process) git add + commit + push",
			Note: "atomic — push failure rolls back the commit",
		})
		add(ScriptInvocation{
			Kind: "bootstrap/flux-install.sh",
			Args: []string{o.Name, "--new-cluster"},
			Note: "wires Flux + applies the new cluster Kustomization",
		})
	}

	// Deferred steps after Flux brings up the components.
	add(ScriptInvocation{
		Kind:          "kube-dc bootstrap openbao init",
		Args:          []string{o.Name},
		DeferredUntil: "HelmRelease/openbao Ready",
		Note:          "share-custody gate (5 shares + root token, fully automated)",
	})
	add(ScriptInvocation{
		Kind:          "hack/openbao-setup-controller-auth.sh",
		DeferredUntil: "OpenBao unsealed",
		Note:          "installs the k8s-host auth method + controller policies",
	})
	add(ScriptInvocation{
		Kind:          "bootstrap/setup-keycloak-oidc.sh",
		Args:          []string{o.Name},
		DeferredUntil: "HelmRelease/keycloak Ready",
	})
	// NOTE (OS-1): the former "(in-process) apply Rook CephObjectStore
	// + system OBCs (deferred until CephCluster.phase=Ready)" step was
	// deleted — it was never implemented AND contradicted the GitOps
	// model: the CephObjectStore + OBCs are Flux-applied via the
	// infra-object-storage Kustomization (healthCheck gates platform on
	// CephCluster Ready). OS-2's scaffold writer emits those files;
	// nothing is ever applied imperatively by the CLI.
	return scripts
}

// warningsForOptions surfaces non-gating consequences of explicit
// operator choices. OS-1: disabled object storage. The explicit
// `--object-storage-mode=disabled` IS the consent (design call
// 2026-07-04 — no extra flag), but the plan must state the outcome.
func warningsForOptions(o *InitOptions) []string {
	var w []string
	// FRONT DOOR — stated only when there is something SURPRISING. Routine
	// information in a warnings block trains operators to ignore warnings, so
	// the plain case (an explicit no-VIP layer with ingress nodes declared)
	// says nothing. What earns a line: an INFERRED choice (the operator did
	// not ask for it), a VIP layer (failover is automatic but slower than
	// people expect), and a missing/singular ingress-node set.
	env, envErr := ResolvedEnvFor(o)
	if envErr != nil {
		env = o.Sets
	}
	layer, ambiguous := resolveAddressLayer(o.IngressAddressLayer,
		env["METALLB_FLOATING_IP"], env["METALLB_MODE"])
	if ambiguous {
		// Validation refuses this, so reaching the plan means validation was
		// bypassed. Do NOT dress the fail-safe up as a decision.
		w = append(w, fmt.Sprintf(
			"front door UNRESOLVED: METALLB_FLOATING_IP=%s is reserved but no address layer claims it. "+
				"The install would fall back to serving on the ingress nodes' own addresses and that VIP would never be announced. "+
				"Pass --ingress-address-layer=metallb-l2 (or =none and drop the reservation).",
			strings.TrimSpace(env["METALLB_FLOATING_IP"])))
	}
	switch layer {
	case AddressLayerMetalLBL2:
		w = append(w,
			"front door: MetalLB L2 VIP — MetalLB IS installed. The VIP moves on node loss automatically, but recovery is memberlist failure detection plus ARP/GARP convergence (seconds to tens of seconds), not instant.")
	case AddressLayerMetalLBBGP:
		w = append(w,
			"front door: MetalLB BGP VIP — MetalLB IS installed. Withdrawal waits out the BGP hold timer (METALLB_BGP_HOLD_TIME, default 90s), so failover is automatic but NOT fast.")
	}
	ingressNodes, ingressFromGW := ResolveIngressNodes(o, env)
	if len(ingressNodes) == 1 {
		w = append(w,
			"only ONE ingress node will carry the front door ("+ingressNodes[0]+"): that node is a single point of failure — two or more is the production shape.")
	}
	// Legal but wasted: a VIP is announced only from a node that is BOTH an
	// external-gateway node and running Envoy (externalTrafficPolicy=Local),
	// so ingress nodes outside the gateway set serve direct-IP traffic and
	// never the VIP. Disjoint sets are a hard error elsewhere; a partial
	// overlap is worth saying out loud because it looks like added capacity.
	if addressLayerRequiresVIP(layer) && !ingressFromGW && len(ingressNodes) > 0 {
		gwSet := map[string]bool{}
		for _, n := range canonicalIngressNodes(strings.Split(env["KUBE_OVN_GW_NODES"], ",")) {
			gwSet[n] = true
		}
		var outside []string
		for _, n := range ingressNodes {
			if !gwSet[n] {
				outside = append(outside, n)
			}
		}
		if len(outside) > 0 && len(outside) < len(ingressNodes) {
			w = append(w, fmt.Sprintf(
				"ingress node(s) %s are NOT external-gateway nodes, so they can never announce the VIP (MetalLB announces only from gateway nodes holding a local Envoy endpoint). They will still serve traffic sent to their own addresses.",
				strings.Join(outside, ", ")))
		}
	}

	// rook-ceph-local is LOOP-FILE backed: its disk-prep Job creates a sparse
	// file and attaches it to a loop device, and CEPH_LOCAL_OSD_DEVICE names that
	// LOOP device (every live cluster on this mode sets loop0; real disks are
	// added afterwards by a per-cluster overlay patch). Naming a real disk here
	// reads as "put Ceph on my NVMe" and does something subtly different, so say
	// what will actually happen rather than refusing a shape that does work.
	if o.RookMode == RookCephLocal && o.RookOSDDevice != "" &&
		!strings.HasPrefix(o.RookOSDDevice, "loop") {
		w = append(w, fmt.Sprintf(
			"object storage: --rook-osd-device=%s names a REAL disk, but rook-ceph-local is loop-file "+
				"backed. Ceph will consume %s directly, AND the disk-prep Job will still create a "+
				"%d GiB sparse backing file and attach it to a free loop device — unused. If you meant "+
				"Ceph on the raw disk, rook-ceph-multi-node is the mode for that; if you meant this "+
				"disk's capacity through a backing file, set --rook-osd-device=loop0 and point "+
				"CEPH_LOCAL_OSD_BACKING_FILE at a filesystem on it.",
			o.RookOSDDevice, o.RookOSDDevice, o.RookOSDSizeGB))
	}

	if o.RookMode == RookDisabled {
		// OS-4 v2: the degraded mode is honest — the exact
		// consequences, not a vague "won't converge".
		w = append(w,
			"object storage disabled (degraded/dev mode): Mimir + Loki are SUSPENDED (no metrics/logs storage); grafana-pg backups + WAL archiving are DISABLED (Grafana DB runs UNPROTECTED); alloy log-delivery errors are expected. NEVER for customer-ready clusters — object storage is load-bearing for metrics, logs, tenant buckets, and backups.")
	}
	if o.GPUPlatform == GPUPlatformDetectOnly {
		w = append(w, "GPU detect-only mode: hardware may be inventoried, but no node owner, runtime stack, tenant profile, creation gate, or billable entitlement is enabled.")
	}
	if o.GPUPlatform == GPUPlatformEnabled {
		w = append(w, "GPU components are privileged; changing an existing node between Shared GPU and Dedicated GPU VM ownership requires a holder-safe drain and may require a reboot. Installer configuration never grants tenant quota.")
		w = append(w, "GPU capacity review is mandatory before commercial enablement: bootstrap publishes no add-on grant, does not compare plan/add-on quantities with physical capacity, and keeps billing plus Pod/VM creation gates closed.")
		w = append(w, "GPU rollback is GitOps-owned: stop new creation, verify zero Pod/VMI holders, then revert the gpu-node-mode/runtime commit; never rebind a driver or change ownership labels under a running holder, and leave a failed transition cordoned.")
		for _, mode := range o.GPUNodeModes {
			if mode == GPUNodeVMPassthrough || mode == GPUNodeVMVGPU {
				w = append(w, "GPU-backed VirtualMachines are non-live-migratable: maintenance, drains, driver changes and ownership rollback require an explicit stop/start or approved evacuation plan; do not rely on KubeVirt LiveMigrate defaults.")
				break
			}
		}
	}
	return w
}

func sopsRecipientsNote(fleet FleetState) string {
	if fleet.SOPSRecipients == 0 {
		return "single recipient (operator's local age key)"
	}
	return fmt.Sprintf("recipients auto-resolved from .sops.yaml: %d age key(s)", fleet.SOPSRecipients)
}

// mutationsForOptions returns the canonical cluster-side mutations.
// T12 will refine with actual GVR shapes; T02 surfaces the
// installer-prd §5.3 baseline.
func mutationsForOptions(o *InitOptions) []Mutation {
	return []Mutation{
		{Kind: "Namespace", Name: "flux-system"},
		{Kind: "GitRepository", Namespace: "flux-system", Name: "flux-system", Note: "gotk-sync"},
		{Kind: "Kustomization", Namespace: "flux-system", Name: "flux-system", Note: "gotk-sync entry pointing at clusters/" + o.Name},
		{Kind: "Secret", Namespace: "flux-system", Name: "sops-age", Note: "age private key (operator's local key)"},
	}
}

func confirmationsForOptions(o *InitOptions) []Confirmation {
	// Per installer-ux §5.3, OpenBao share custody is fully automated
	// — no interactive gate. The only TTY confirmation is the final
	// "apply plan?" prompt, which --yes / --apply-plan / --dry-run
	// also bypass. Return an empty list explicitly so the plan's
	// "Confirmations required" section renders the "(none)" line.
	_ = o
	return []Confirmation{}
}

// skippedForOptions returns the "Files NOT touched" / "Skipped" list
// for existing-fleet renders. Empty for new-repo.
func skippedForOptions(o *InitOptions, fleet FleetState) []string {
	if o.FleetMode != FleetExistingFleet {
		return nil
	}
	skipped := []string{
		"infrastructure/ (shared base — managed by OCI bundle)",
		"platform/ (shared base)",
		"addons/ (shared base)",
		".sops.yaml (already includes operator's pubkey)",
	}
	for _, name := range fleet.PriorClusters {
		skipped = append(skipped, "clusters/"+name+"/ (untouched)")
	}
	sort.Strings(skipped)
	return skipped
}

// --- Render ---

// Render writes the human-readable plan preview to w. The shape
// mirrors installer-ux §5.3 (greenfield) and §5.5 (existing-fleet).
// Existing-fleet adds the "Detected: existing-fleet at . " header +
// "Files NOT touched" section.
func (p *Plan) Render(w io.Writer) {
	if p.FleetMode == FleetExistingFleet {
		fmt.Fprintln(w, "== Detected: existing-fleet ==")
		if len(p.PriorClusters) > 0 {
			fmt.Fprintf(w, "   Prior clusters: %s\n", strings.Join(p.PriorClusters, ", "))
		}
		if p.InheritanceTemplate != "" {
			fmt.Fprintf(w, "   Template (most-recently-modified sibling): %s\n", p.InheritanceTemplate)
		}
		if len(p.InheritedDefaults) > 0 {
			fmt.Fprintf(w, "   Inherited defaults (%d version pins; override with --set):\n", len(p.InheritedDefaults))
			keys := make([]string, 0, len(p.InheritedDefaults))
			for k := range p.InheritedDefaults {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				fmt.Fprintf(w, "     %s=%s\n", k, p.InheritedDefaults[k])
			}
		}
		fmt.Fprintln(w)
	}

	starterRef := p.StarterRef
	if starterRef == "" {
		starterRef = "<not resolved>"
	}
	sharesOut := p.OpenBaoSharesOut
	if sharesOut == "" {
		sharesOut = "<not requested; encrypted fleet copy remains authoritative>"
	}
	fmt.Fprintln(w, "== Reviewed inputs ==")
	fmt.Fprintf(w, " Cluster: %s (%s)\n", p.ClusterName, p.Domain)
	fmt.Fprintf(w, " Starter: %s\n", starterRef)
	fmt.Fprintf(w, " OpenBao shares-out: %s\n", sharesOut)
	// Always printed: the front door is the fact operators most often learn
	// AFTER the install instead of during the review.
	if p.FrontDoor != "" {
		fmt.Fprintf(w, " Front door: %s\n", p.FrontDoor)
	}
	if p.TrustedCAFingerprint != "" {
		fmt.Fprintf(w, " Private-CA sha256: %s\n", p.TrustedCAFingerprint)
	}
	fmt.Fprintln(w)

	if len(p.Warnings) > 0 {
		fmt.Fprintln(w, "== WARNINGS ==")
		for _, warn := range p.Warnings {
			fmt.Fprintf(w, " ⚠ %s\n", warn)
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintf(w, "== Files to write (clusters/%s/) ==\n", p.ClusterName)
	for _, f := range p.FilesToWrite {
		fmt.Fprintf(w, " %s %s — %s\n", f.Action, f.Path, f.Description)
	}

	if len(p.SkippedExistingFleet) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "== Files NOT touched (already in fleet) ==")
		for _, s := range p.SkippedExistingFleet {
			fmt.Fprintf(w, " - %s\n", s)
		}
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "== Scripts to run ==")
	for _, s := range p.ScriptsToRun {
		marker := ""
		if s.DeferredUntil != "" {
			marker = " (deferred until " + s.DeferredUntil + ")"
		}
		args := ""
		if len(s.Args) > 0 {
			args = " " + strings.Join(s.Args, " ")
		}
		fmt.Fprintf(w, " [%2d] %s%s%s\n", s.Index, s.Kind, args, marker)
		if s.Note != "" {
			fmt.Fprintf(w, "      %s\n", s.Note)
		}
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "== Cluster mutations ==")
	for _, m := range p.ClusterMutations {
		ns := ""
		if m.Namespace != "" {
			ns = m.Namespace + "/"
		}
		note := ""
		if m.Note != "" {
			note = " — " + m.Note
		}
		fmt.Fprintf(w, " + %s/%s%s%s\n", m.Kind, ns, m.Name, note)
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "== Confirmations required ==")
	if len(p.ConfirmationsRequired) == 0 {
		fmt.Fprintln(w, " (none in --no-tty mode; --yes applies the full plan unattended)")
		fmt.Fprintln(w, " (TTY mode: one final \"apply plan? [y/N]\" prompt before mutations start)")
	}
	for _, c := range p.ConfirmationsRequired {
		def := "n"
		if c.Default {
			def = "y"
		}
		fmt.Fprintf(w, " - %s: %s [%s]\n", c.ID, c.Prompt, def)
	}

	fmt.Fprintln(w)
	fmt.Fprintf(w, "Plan: %d scripts, %d files, %d cluster mutations, 0 destructive gates.\n",
		len(p.ScriptsToRun), len(p.FilesToWrite), len(p.ClusterMutations))
	fmt.Fprintf(w, "InputHash: %s\nPlanHash:  %s\n", p.InputHash, p.PlanHash)
	fmt.Fprintln(w, "Pass --yes to apply, --apply-plan <plan.json> to apply hash-pinned.")
}

// --- File I/O ---

// WritePlanFile atomically writes `p`'s canonical JSON to `path`.
//
// Atomicity contract:
//
//   - Writes to a unique temp file via `os.CreateTemp(dir, base+".*.tmp")`
//     so concurrent writes to the same destination don't collide
//     (M4-T01+T02 review-pass — P3).
//   - Renames the temp file into place; the rename is atomic on POSIX
//     filesystems within the same directory.
//   - On failure at any step, the temp file is removed; the
//     destination is never partially-written.
//
// Mode 0644 — the plan contains no secret material since InputHash
// is a one-way hash and GitHubToken is excluded from the hash
// projection (see `inputsForHash` doc).
func WritePlanFile(p *Plan, path string) error {
	data, err := canonicalJSON(p)
	if err != nil {
		return fmt.Errorf("canonical-JSON plan: %w", err)
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	// Unique temp file in the destination directory (same FS so the
	// rename is atomic on POSIX). Pattern `<base>.*.tmp` keeps the
	// suffix predictable for debugging — `.*` is replaced with a
	// random token by os.CreateTemp.
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".*.tmp")
	if err != nil {
		return fmt.Errorf("create temp in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	if _, werr := tmp.Write(data); werr != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("write temp %s: %w", tmpPath, werr)
	}
	// Match the old behaviour: world-readable, owner-writable. CreateTemp
	// defaults to 0600 — we explicitly broaden to 0644 because the
	// plan is not secret and operators may want to inspect it
	// without sudo (the .tmp file is short-lived but the rename
	// inherits the mode).
	if err := tmp.Chmod(0o644); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("chmod temp %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("close temp %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("rename %s -> %s: %w", tmpPath, path, err)
	}
	return nil
}

// LoadPlan reads the plan JSON from `path` and verifies both the
// schema version and the PlanHash. Returns ErrPlanSchemaVersion or
// ErrPlanHashMismatch on tamper/version drift.
func LoadPlan(path string) (*Plan, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read plan %s: %w", path, err)
	}
	var p Plan
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parse plan %s: %w", path, err)
	}
	if p.Version != PlanSchemaVersion {
		return nil, fmt.Errorf("%w (got %q, want %q)", ErrPlanSchemaVersion, p.Version, PlanSchemaVersion)
	}
	want, err := p.computeHash()
	if err != nil {
		return nil, fmt.Errorf("verify plan hash: %w", err)
	}
	if want != p.PlanHash {
		return nil, fmt.Errorf("%w (computed %s, file %s)", ErrPlanHashMismatch, want, p.PlanHash)
	}
	return &p, nil
}

// VerifyApplyPlanInput recomputes InputHash from `o` and compares to
// `p.InputHash`. Returns ErrPlanInputDrift on mismatch.
func VerifyApplyPlanInput(p *Plan, o *InitOptions) error {
	want, err := ComputeInputHash(o)
	if err != nil {
		return err
	}
	if want != p.InputHash {
		return fmt.Errorf("%w (plan inputHash=%s; current=%s)", ErrPlanInputDrift, p.InputHash, want)
	}
	return nil
}

// --- Consent cache ---

// ConsentMarker is the small JSON file that a successful --dry-run
// writes to ~/.kube-dc/init-state/<cluster>-dry-run-ok.json. It is
// not a resume token — purely a local "yes, this exact plan was just
// reviewed" signal so `--no-tty` apply can proceed without --yes.
type ConsentMarker struct {
	ClusterName string    `json:"clusterName"`
	PlanHash    string    `json:"planHash"`
	GeneratedAt time.Time `json:"generatedAt"`
}

// ConsentMarkerPath returns the canonical on-disk path for a cluster's
// consent marker. Indirected through a package var so tests can
// substitute a tmpdir.
var consentDir = func() string {
	if home, err := os.UserHomeDir(); err == nil {
		return filepath.Join(home, ".kube-dc", "init-state")
	}
	return os.TempDir()
}

func ConsentMarkerPath(cluster string) string {
	// Cluster names can contain '/' (eu/dc1 shape) — flatten so the
	// marker file is one path component.
	safe := strings.ReplaceAll(cluster, "/", "_")
	return filepath.Join(consentDir(), safe+"-dry-run-ok.json")
}

// WriteConsentMarker writes the marker for a freshly-dry-run plan.
// Existing marker is overwritten (a fresh dry-run is the latest
// consent). Uses the same unique-temp + rename pattern as
// WritePlanFile so concurrent dry-runs of distinct clusters can't
// collide on the temp suffix.
func WriteConsentMarker(p *Plan) error {
	m := ConsentMarker{
		ClusterName: p.ClusterName,
		PlanHash:    p.PlanHash,
		GeneratedAt: time.Now().UTC().Truncate(time.Second),
	}
	data, err := json.Marshal(m)
	if err != nil {
		return fmt.Errorf("marshal consent marker: %w", err)
	}
	path := ConsentMarkerPath(p.ClusterName)
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".*.tmp")
	if err != nil {
		return fmt.Errorf("create temp in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	if _, werr := tmp.Write(data); werr != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("write %s: %w", tmpPath, werr)
	}
	if err := tmp.Chmod(0o644); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("chmod %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("close %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("rename %s -> %s: %w", tmpPath, path, err)
	}
	return nil
}

// LookupConsentMarker reads the marker for `cluster` and reports
// whether its PlanHash matches `wantHash`. Returns (false, nil) if no
// marker exists; (false, err) on parse/IO failure; (true, nil) on
// match. A non-match is (false, nil) so the cobra layer can surface a
// clean "no consent for this plan; re-run --dry-run" message rather
// than a stack trace.
func LookupConsentMarker(cluster, wantHash string) (bool, error) {
	path := ConsentMarkerPath(cluster)
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("read consent marker %s: %w", path, err)
	}
	var m ConsentMarker
	if err := json.Unmarshal(data, &m); err != nil {
		return false, fmt.Errorf("parse consent marker %s: %w", path, err)
	}
	return m.PlanHash == wantHash, nil
}
