service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: ""
  hostname: wordpress.kube-dc.com
  annotations:
    cert-manager.io/issuer: letsencrypt-http
  tls: true

networkPolicy:
  enabled: false

mariadb:
  networkPolicy:
    enabled: false
