service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: wordpress.stage.kube-dc.com
  annotations:
    cert-manager.io/issuer: letsencrypt-http
  tls: true

extraEnvVars:
  - name: WORDPRESS_SITE_URL
    value: "https://wordpress.stage.kube-dc.com"
  - name: WORDPRESS_BLOG_NAME
    value: "My Blog"


networkPolicy:
  enabled: false

mariadb:
  networkPolicy:
    enabled: false
