apiVersion: kube-dc.com/v1
kind: OrganizationGroup
metadata:
  name: "{group}"
  namespace: "{organization}"          # Organization API namespace
spec:
  permissions:
    - project: "{project}"             # Project name, not backing namespace
      roles:
        - developer                  # admin | developer | project-manager | user
    - project: "{another-project}"
      roles:
        - project-manager
