version: 2
project_name: kube-dc

before:
  hooks:
    - go mod tidy

builds:
  - id: kube-dc
    main: ./cmd/kube-dc
    binary: kube-dc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: kube-dc
    name: kube-dc-public
  prerelease: auto
  name_template: "kube-dc CLI v{{.Version}}"
