node-name: kube-dc-master-1
disable-cloud-controller: true
disable: rke2-ingress-nginx
cni: none
cluster-cidr: "10.100.0.0/16"
service-cidr: "10.101.0.0/16"
cluster-dns: "10.101.0.11"
node-label:
  - kube-dc-manager=true
  - kube-ovn/role=master
kube-apiserver-arg: 
  - authentication-config=/etc/rancher/auth-conf.yaml
debug: true
node-external-ip: 88.99.29.250 # Main IP provided by Hetzner for server
tls-san:
  - kube-api.stage.kube-dc.com
  - 88.99.29.250
  - 192.168.1.3
advertise-address: 192.168.1.3
node-ip: 192.168.1.3
