package log

import (
	"bytes"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

// helper: build a Logger that writes its file into t.TempDir() and
// captures stdout via an in-memory buffer. Returns the buffer plus the
// path to the file so tests can read it back.
//
// Tests pin a fixed correlation ID by default so the filename
// (kube-dc-<rfc3339>-<cid-prefix>.log) is deterministic; tests that
// need an auto-generated ID call New directly.
func newTestLogger(t *testing.T, opts Options) (*Logger, *bytes.Buffer, string) {
	t.Helper()
	dir := t.TempDir()
	out := &bytes.Buffer{}
	opts.Dir = dir
	if opts.Stdout == nil {
		opts.Stdout = out
	}
	if opts.NowFn == nil {
		fixed := time.Date(2026, 5, 25, 12, 34, 56, 0, time.UTC)
		opts.NowFn = func() time.Time { return fixed }
	}
	if opts.CorrelationID == "" {
		opts.CorrelationID = "12345678-aaaa-4bbb-8ccc-dddddddddddd"
	}
	if !opts.ForceJSON && !opts.ForceText {
		opts.ForceJSON = true // deterministic format in tests
	}
	lg, err := New(opts)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	t.Cleanup(func() { _ = lg.Close() })

	want := filepath.Join(dir,
		"kube-dc-2026-05-25T12-34-56Z-"+shortCorrelationID(opts.CorrelationID)+".log")
	return lg, out, want
}

func readLogLines(t *testing.T, path string) []map[string]any {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read log file: %v", err)
	}
	lines := bytes.Split(bytes.TrimSpace(raw), []byte("\n"))
	out := make([]map[string]any, 0, len(lines))
	for _, ln := range lines {
		if len(ln) == 0 {
			continue
		}
		var rec map[string]any
		if err := json.Unmarshal(ln, &rec); err != nil {
			t.Fatalf("unmarshal %q: %v", ln, err)
		}
		out = append(out, rec)
	}
	return out
}

func TestFileRotation_FileExistsAfterInfo(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	lg.Info("hello")
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("log file %s: %v", path, err)
	}
}

func TestCorrelationID_StampedOnEveryLine(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{CorrelationID: "fixed-cid-1234"})
	lg.Info("one")
	lg.Warn("two")
	lg.Error("three")
	for _, rec := range readLogLines(t, path) {
		got, _ := rec[CorrelationIDKey].(string)
		if got != "fixed-cid-1234" {
			t.Errorf("record missing correlation_id: %v", rec)
		}
	}
}

func TestCorrelationID_AutoGenerated_IsUUIDv4(t *testing.T) {
	// Bypass newTestLogger's fixed-CID default — we need the auto path.
	lg, err := New(Options{
		Dir:       t.TempDir(),
		Stdout:    io.Discard,
		ForceJSON: true,
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	defer lg.Close()
	cid := lg.CorrelationID()
	re := regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)
	if !re.MatchString(cid) {
		t.Errorf("CorrelationID() = %q, want UUIDv4", cid)
	}
}

// Layer 1 — field-key redaction.
func TestRedact_Layer1_FieldName(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})

	cases := []struct {
		key string
	}{
		{"share_2"},
		{"token"},
		{"GITHUB_TOKEN"},
		{"password"},
		{"secret"},
		{"unseal_key"},
		{"ssh_key"},
		{"age_key"},
	}
	for _, c := range cases {
		lg.Info("layer1", c.key, "abc123")
	}

	records := readLogLines(t, path)
	if len(records) < len(cases) {
		t.Fatalf("got %d records, want %d", len(records), len(cases))
	}
	for i, c := range cases {
		got := records[i][c.key]
		if got != RedactedMarker {
			t.Errorf("layer-1 key %q: got %v, want %q", c.key, got, RedactedMarker)
		}
	}
}

// Layer 1 — non-matching keys are not touched.
func TestRedact_Layer1_NonMatching(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	lg.Info("benign", "node_name", "node-c3", "namespace", "openbao")
	records := readLogLines(t, path)
	if got := records[0]["node_name"]; got != "node-c3" {
		t.Errorf("node_name redacted unexpectedly: %v", got)
	}
	if got := records[0]["namespace"]; got != "openbao" {
		t.Errorf("namespace redacted unexpectedly: %v", got)
	}
}

// Layer 2 — adjacent-key/value redaction.
func TestRedact_Layer2_AdjacentKeyValue(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	lg.Info("layer2", "key", "OPENBAO_UNSEAL_KEY_1", "value", "abc123")
	records := readLogLines(t, path)
	if got := records[0]["value"]; got != RedactedMarker {
		t.Errorf("layer-2 value: got %v, want %q", got, RedactedMarker)
	}
	// The `key` field itself ends in "key" so layer-1 redacts it. That's
	// correct: by the time we've consumed it for the adjacency check,
	// keeping its plaintext provides no operator benefit and could leak
	// in nested structured calls.
	if got := records[0]["key"]; got != RedactedMarker {
		t.Errorf("layer-2 key (post-adjacency): got %v, want %q", got, RedactedMarker)
	}
}

// Layer 2 — when `key` does NOT carry a secret-name marker, `value`
// is left untouched.
func TestRedact_Layer2_BenignKeyValue(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	lg.Info("benign-kv", "key", "node_name", "value", "node-c3")
	records := readLogLines(t, path)
	if got := records[0]["value"]; got != "node-c3" {
		t.Errorf("benign value got redacted: %v", got)
	}
}

// Layer 2 across With() — secret-key context attached via With() must
// redact a `value:` attr in subsequent records, otherwise the
// canonical share-iteration pattern
//
//	for i, share := range shares {
//	    lg.With("key", fmt.Sprintf("OPENBAO_UNSEAL_KEY_%d", i+1)).
//	        Info("storing", "value", share)
//	}
//
// would leak every share. Covers the P1 finding from the M0-T05
// review of commit 2902fc62.
func TestRedact_Layer2_WithKeyContextRedactsRecordValue(t *testing.T) {
	parent, _, path := newTestLogger(t, Options{})
	child := parent.With("key", "OPENBAO_UNSEAL_KEY_1")
	child.Info("storing", "value", "abc123")
	records := readLogLines(t, path)
	if got := records[0]["value"]; got != RedactedMarker {
		t.Errorf("value not redacted across With(key=...): got %v want %q", got, RedactedMarker)
	}
}

// Layer 2 in a single With() call — both `key:` and `value:` passed
// together must redact `value` at construction time, so the inner
// handler never stores the raw secret.
func TestRedact_Layer2_WithKeyValueSameWithAttrs(t *testing.T) {
	parent, _, path := newTestLogger(t, Options{})
	child := parent.With("key", "OPENBAO_UNSEAL_KEY_2", "value", "abc-shouldnt-leak")
	child.Info("contextual")
	records := readLogLines(t, path)
	if got := records[0]["value"]; got != RedactedMarker {
		t.Errorf("value not redacted in same WithAttrs call: got %v want %q", got, RedactedMarker)
	}
	if strings.Contains(records[0]["value"].(string), "abc-shouldnt-leak") {
		t.Errorf("raw value leaked: %v", records[0]["value"])
	}
}

// Layer 2 context inherits through chained With() and WithGroup() so
// the propagation rule survives realistic logger plumbing.
func TestRedact_Layer2_ContextInheritsThroughChain(t *testing.T) {
	parent, _, path := newTestLogger(t, Options{})
	chain := parent.
		With("key", "OPENBAO_UNSEAL_KEY_3").
		With("node", "node-c3") // benign extension
	chain.Info("chained", "value", "still-secret")
	records := readLogLines(t, path)
	if got := records[0]["value"]; got != RedactedMarker {
		t.Errorf("inherited context did not redact value: got %v want %q", got, RedactedMarker)
	}
	if got := records[0]["node"]; got != "node-c3" {
		t.Errorf("benign attr got redacted by inheritance: %v", got)
	}
}

// Sibling loggers — context tainted ONE child must NOT bleed back
// into the parent or into an unrelated child.
func TestRedact_Layer2_ContextDoesNotBleedToSiblings(t *testing.T) {
	parent, _, path := newTestLogger(t, Options{})

	// Tainted child.
	tainted := parent.With("key", "OPENBAO_UNSEAL_KEY_4")
	tainted.Info("tainted", "value", "secret-x")

	// Parent itself logs a benign value=.
	parent.Info("parent-log", "key", "node_name", "value", "node-b2")

	records := readLogLines(t, path)
	if len(records) < 2 {
		t.Fatalf("want 2 records, got %d", len(records))
	}
	if records[0]["value"] != RedactedMarker {
		t.Errorf("tainted child did not redact: %v", records[0]["value"])
	}
	if records[1]["value"] != "node-b2" {
		t.Errorf("parent value got redacted via sibling bleed: %v", records[1]["value"])
	}
}

// Layer 3 — env map walking inside an attr.
func TestRedact_Layer3_EnvMap(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	env := map[string]string{
		"GITHUB_TOKEN":   "ghp_xxx",
		"FLEET_BRANCH":   "main",
		"OPENBAO_TOKEN":  "abc.def",
		"KUBE_DC_RELEASE": "v0.3.62",
	}
	lg.Info("script-exec", "env", env)
	records := readLogLines(t, path)
	got, ok := records[0]["env"].(map[string]any)
	if !ok {
		t.Fatalf("env not a map: %v", records[0]["env"])
	}
	if got["GITHUB_TOKEN"] != RedactedMarker {
		t.Errorf("GITHUB_TOKEN: got %v", got["GITHUB_TOKEN"])
	}
	if got["OPENBAO_TOKEN"] != RedactedMarker {
		t.Errorf("OPENBAO_TOKEN: got %v", got["OPENBAO_TOKEN"])
	}
	if got["FLEET_BRANCH"] != "main" {
		t.Errorf("FLEET_BRANCH redacted unexpectedly: %v", got["FLEET_BRANCH"])
	}
	if got["KUBE_DC_RELEASE"] != "v0.3.62" {
		t.Errorf("KUBE_DC_RELEASE redacted unexpectedly: %v", got["KUBE_DC_RELEASE"])
	}
}

// Layer 3 — RedactEnv exported helper standalone.
func TestRedactEnv_Helper(t *testing.T) {
	got := RedactEnv(map[string]string{
		"GITHUB_TOKEN": "ghp_xxx",
		"FLEET_BRANCH": "main",
	})
	if got["GITHUB_TOKEN"] != RedactedMarker {
		t.Errorf("GITHUB_TOKEN: %v", got["GITHUB_TOKEN"])
	}
	if got["FLEET_BRANCH"] != "main" {
		t.Errorf("FLEET_BRANCH: %v", got["FLEET_BRANCH"])
	}
}

// Layer 4 — stream-line redaction patterns.
func TestRedactStreamLine_OpenBaoJSON(t *testing.T) {
	in := `Bootstrap output: {"unseal_keys_b64": ["abcdEFGH1234567890abcdEFGH1234567890abcd"], "root_token": "s.xyzAAAAAAAAAAAAAAAAAAAAA"}`
	out := RedactStreamLine(in)
	if strings.Contains(out, "abcdEFGH") {
		t.Errorf("share material leaked: %q", out)
	}
	if strings.Contains(out, "s.xyz") {
		t.Errorf("root token leaked: %q", out)
	}
	if !strings.Contains(out, "unseal_keys_b64") || !strings.Contains(out, RedactedMarker) {
		t.Errorf("redaction did not preserve key names + marker: %q", out)
	}
}

func TestRedactStreamLine_AgeSecretKey(t *testing.T) {
	// 58 char body after AGE-SECRET-KEY-1
	body := strings.Repeat("A", 58)
	in := "Importing identity: AGE-SECRET-KEY-1" + body
	out := RedactStreamLine(in)
	if strings.Contains(out, body) || strings.Contains(out, "AGE-SECRET-KEY-1") {
		t.Errorf("age secret key leaked: %q", out)
	}
}

func TestRedactStreamLine_AgeRecipient(t *testing.T) {
	in := "Recipient: age10mskwx065akee5mw4txeqtnn90t724phdzx9k4jxnrgcp9cces6sqfkwvu OK"
	out := RedactStreamLine(in)
	if strings.Contains(out, "age10mskwx") {
		t.Errorf("age recipient leaked: %q", out)
	}
}

func TestRedactStreamLine_Base64WithSecretContext(t *testing.T) {
	in := "share captured: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdef=="
	out := RedactStreamLine(in)
	if strings.Contains(out, "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890") {
		t.Errorf("base64 share leaked: %q", out)
	}
	if !strings.Contains(out, RedactedMarker) {
		t.Errorf("missing marker: %q", out)
	}
}

func TestRedactStreamLine_Base64WithoutSecretContext_NotMasked(t *testing.T) {
	// An image digest is base64-ish, but no secret-context word triggers the gate.
	in := "Pushing image: registry/foo@sha256:ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdef"
	out := RedactStreamLine(in)
	if !strings.Contains(out, "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890") {
		t.Errorf("digest got masked without secret context: %q", out)
	}
}

// Layer 5 — sentinel placeholder is emitted as a normal info line and
// doesn't trigger redaction itself.
func TestSentinelPlaceholder_PassThroughClean(t *testing.T) {
	placeholder := SentinelPlaceholder("openbao-init.sh", "5 shares, root token")
	out := RedactStreamLine(placeholder)
	if out != placeholder {
		t.Errorf("placeholder got mutated: input=%q output=%q", placeholder, out)
	}
	if strings.Contains(placeholder, "abc") || strings.Contains(placeholder, "[REDACTED]") {
		// not testing exact form — just that placeholder is descriptive and not a literal payload
	}
}

// Defense-in-depth: if a sentinel payload DID leak into Info, layer 4
// would still mask it. The runner calls log.Info(SentinelPlaceholder(…))
// for the success path; the test below simulates the failure path
// where a future bug accidentally calls Info with the raw payload.
func TestRedactStreamLine_DefenseInDepth_OpenBaoPayload(t *testing.T) {
	in := `{"unseal_keys_b64":["a1","b2","c3","d4","e5"],"root_token":"s.rootABCDEF"}`
	out := RedactStreamLine(in)
	if strings.Contains(out, "s.rootABCDEF") {
		t.Errorf("payload leaked: %q", out)
	}
}

func TestVerboseFlag_LowersToDebug(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{Verbose: true})
	lg.Debug("verbose-debug")
	lg.Info("verbose-info")
	records := readLogLines(t, path)
	if len(records) < 2 {
		t.Fatalf("verbose: got %d records, want >=2", len(records))
	}
}

func TestNonVerbose_DropsDebug(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	lg.Debug("ignored")
	lg.Info("kept")
	records := readLogLines(t, path)
	if len(records) != 1 {
		t.Fatalf("non-verbose: got %d records, want 1", len(records))
	}
	if records[0]["msg"] != "kept" {
		t.Errorf("kept wrong record: %v", records[0])
	}
}

func TestTeeChannel_EmitsLines(t *testing.T) {
	lg, _, _ := newTestLogger(t, Options{})
	tee := lg.Tee()

	done := make(chan string, 4)
	go func() {
		for line := range tee {
			done <- line
		}
	}()

	lg.Info("tee-test", "answer", 42)
	// give the tee writer a moment to flush
	time.Sleep(20 * time.Millisecond)

	select {
	case ln := <-done:
		if !strings.Contains(ln, "tee-test") {
			t.Errorf("tee got %q, want substring 'tee-test'", ln)
		}
	case <-time.After(500 * time.Millisecond):
		t.Fatal("tee channel emitted nothing within deadline")
	}
}

func TestTeeChannel_DropOldestWhenFull(t *testing.T) {
	// Build a logger but DON'T drain the tee. After writing more than
	// teeBufferLines records, Write must still succeed (non-blocking).
	lg, _, _ := newTestLogger(t, Options{})
	for i := 0; i < teeBufferLines*2; i++ {
		lg.Info("drop-test", "i", i)
	}
	// If teeWriter blocked, the loop would hang and t fails on timeout.
}

func TestWith_RedactsAtConstruction(t *testing.T) {
	parent, _, path := newTestLogger(t, Options{})
	child := parent.With("token", "should-be-redacted", "node", "ams1")
	child.Info("with-test")

	records := readLogLines(t, path)
	if records[0]["token"] != RedactedMarker {
		t.Errorf("With() did not redact token: %v", records[0]["token"])
	}
	if records[0]["node"] != "ams1" {
		t.Errorf("With() leaked non-secret: %v", records[0]["node"])
	}
}

func TestStdoutSink_DiscardableInTUIMode(t *testing.T) {
	// io.Discard stdout simulates TUI mode — no panic on Info.
	lg, err := New(Options{
		Dir:           t.TempDir(),
		Stdout:        io.Discard,
		CorrelationID: "tui-mode",
		NowFn:         func() time.Time { return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC) },
	})
	if err != nil {
		t.Fatalf("New(TUI mode): %v", err)
	}
	defer lg.Close()
	lg.Info("tui-mode")
}

func TestClose_Idempotent(t *testing.T) {
	lg, _, _ := newTestLogger(t, Options{})
	if err := lg.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}
	if err := lg.Close(); err != nil {
		t.Fatalf("Close (second): %v", err)
	}
}

func TestNewCorrelationID_Uniqueness(t *testing.T) {
	seen := map[string]bool{}
	for i := 0; i < 32; i++ {
		id := newCorrelationID()
		if seen[id] {
			t.Errorf("duplicate UUID: %s", id)
		}
		seen[id] = true
	}
}

// Filename includes the correlation-ID prefix so two CLI invocations
// landing in the same wall-clock second produce DIFFERENT files —
// O_EXCL would otherwise fail-loud on the second open. Covers the
// "log file is not guaranteed per invocation" follow-up from the
// M0-T05 review.
func TestFilename_UniquePerInvocationInSameSecond(t *testing.T) {
	dir := t.TempDir()
	fixed := time.Date(2026, 5, 25, 12, 34, 56, 0, time.UTC)
	mk := func(cid string) *Logger {
		lg, err := New(Options{
			Dir:           dir,
			Stdout:        io.Discard,
			NowFn:         func() time.Time { return fixed },
			CorrelationID: cid,
			ForceJSON:     true,
		})
		if err != nil {
			t.Fatalf("New(%s): %v", cid, err)
		}
		t.Cleanup(func() { _ = lg.Close() })
		return lg
	}

	mk("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
	mk("bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb")

	entries, err := filepath.Glob(filepath.Join(dir, "kube-dc-*.log"))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		t.Fatalf("got %d log files in same second, want 2 distinct: %v", len(entries), entries)
	}
}

// Filename collision (same time + same CID) is rejected by O_EXCL.
// Vanishingly unlikely in production (UUIDv4 inside one second), but
// the contract is "fail loud, don't silently append."
func TestFilename_O_EXCLRejectsCollision(t *testing.T) {
	dir := t.TempDir()
	fixed := time.Date(2026, 5, 25, 12, 34, 56, 0, time.UTC)
	cid := "cccccccc-cccc-4ccc-8ccc-cccccccccccc"
	first, err := New(Options{
		Dir:           dir,
		Stdout:        io.Discard,
		NowFn:         func() time.Time { return fixed },
		CorrelationID: cid,
		ForceJSON:     true,
	})
	if err != nil {
		t.Fatalf("first New: %v", err)
	}
	t.Cleanup(func() { _ = first.Close() })

	_, err = New(Options{
		Dir:           dir,
		Stdout:        io.Discard,
		NowFn:         func() time.Time { return fixed },
		CorrelationID: cid,
		ForceJSON:     true,
	})
	if err == nil {
		t.Fatal("New on existing path returned nil error; want EEXIST surface")
	}
}

// Message redaction (defense-in-depth) — even if a future caller
// passes a raw script line or err.Error() that contains secret
// material, RedactStreamLine still masks it before the inner handler
// sees Record.Message.
func TestMessageRedaction_AGESecretKeyInMessage(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	body := strings.Repeat("A", 58)
	raw := "imported identity AGE-SECRET-KEY-1" + body
	lg.Info(raw)
	records := readLogLines(t, path)
	msg, _ := records[0]["msg"].(string)
	if strings.Contains(msg, body) || strings.Contains(msg, "AGE-SECRET-KEY-1") {
		t.Errorf("age secret key leaked into Record.Message: %q", msg)
	}
}

func TestMessageRedaction_OpenBaoPayloadInMessage(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	raw := `bootstrap output {"unseal_keys_b64":["aaaaaaaa","bbbbbbbb"],"root_token":"s.payloadShouldNotLeak"}`
	lg.Error(raw)
	records := readLogLines(t, path)
	msg, _ := records[0]["msg"].(string)
	if strings.Contains(msg, "s.payloadShouldNotLeak") {
		t.Errorf("root token leaked into Record.Message: %q", msg)
	}
}

// Benign messages pass through unchanged — confirms RedactStreamLine
// is conservative enough to apply on every record without mangling
// normal logs (image digests, namespace names, etc.).
func TestMessageRedaction_BenignMessagesPassThrough(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	cases := []string{
		"Reconciled project foo",
		"Pushed image registry/foo@sha256:abcdef1234567890abcdef1234567890abcdef12",
		"Mode=install Phase=4 Steps=12",
	}
	for _, c := range cases {
		lg.Info(c)
	}
	records := readLogLines(t, path)
	for i, c := range cases {
		got, _ := records[i]["msg"].(string)
		if got != c {
			t.Errorf("benign message mangled: input=%q output=%q", c, got)
		}
	}
}

// Nested map redaction — `map[string]any` nested inside another
// `map[string]any` must be walked recursively, otherwise a payload
// like `{"meta": {"token": "abc"}}` leaks the inner token because the
// outer key "meta" doesn't match the secret regex.
func TestRedactNestedMap_AnyMap(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	payload := map[string]any{
		"meta": map[string]any{
			"token":     "secret-token",
			"node_name": "node-c3",
		},
	}
	lg.Info("nested", "payload", payload)

	records := readLogLines(t, path)
	got, _ := records[0]["payload"].(map[string]any)
	meta, _ := got["meta"].(map[string]any)
	if meta["token"] != RedactedMarker {
		t.Errorf("nested token not redacted: %v", meta["token"])
	}
	if meta["node_name"] != "node-c3" {
		t.Errorf("nested benign mangled: %v", meta["node_name"])
	}
}

// Nested string-map inside any-map.
func TestRedactNestedMap_StringMapInAnyMap(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	env := map[string]string{"GITHUB_TOKEN": "ghp_xxx", "FLEET_BRANCH": "main"}
	payload := map[string]any{"env": env}
	lg.Info("nested-env", "payload", payload)

	records := readLogLines(t, path)
	got, _ := records[0]["payload"].(map[string]any)
	gotEnv, _ := got["env"].(map[string]any)
	if gotEnv["GITHUB_TOKEN"] != RedactedMarker {
		t.Errorf("nested string-map token not redacted: %v", gotEnv["GITHUB_TOKEN"])
	}
	if gotEnv["FLEET_BRANCH"] != "main" {
		t.Errorf("nested string-map benign mangled: %v", gotEnv["FLEET_BRANCH"])
	}
}

// Slice of maps inside an any-map.
func TestRedactNestedMap_SliceOfMaps(t *testing.T) {
	lg, _, path := newTestLogger(t, Options{})
	items := []any{
		map[string]any{"token": "t1", "name": "alice"},
		map[string]any{"token": "t2", "name": "bob"},
	}
	lg.Info("nested-slice", "items", items)

	records := readLogLines(t, path)
	got, _ := records[0]["items"].([]any)
	for i, raw := range got {
		entry, _ := raw.(map[string]any)
		if entry["token"] != RedactedMarker {
			t.Errorf("slice[%d].token not redacted: %v", i, entry["token"])
		}
	}
}
