apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: test-linstor2
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 14Gi
    storageClassName: linstor-bs2
  source:
    http:
      url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img