apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replicated-volume
spec:
  storageClassName: linstor-bs2
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce