apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-bs3
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: pool2
  linstor.csi.linbit.com/placementCount: "3"