apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-bs2
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
# volumeBindingMode: Immediate
volumeBindingMode: WaitForFirstConsumer 
parameters:
  linstor.csi.linbit.com/storagePool: pool1
  linstor.csi.linbit.com/placementCount: "2"