apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-lb-node-selector
spec:
  rules:
  - name: set-lb-node-selector
    match:
      any:
      - resources:
          kinds:
          - Deployment
          name: "lb-svc-*" 
    mutate:
      patchStrategicMerge:
        spec:
          template:
            spec:
              nodeSelector:
                external-network: "true"