apiVersion: v1
kind: Pod
metadata:
  name: iso-upload-pod
  namespace: iso
spec:
  restartPolicy: Never
  containers:
  - name: uploader
    image: busybox:1.36
    command: ["sleep", "3600"]
    volumeMounts:
    - name: storage
      mountPath: /storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: iso-storage
