apiVersion: v1
kind: Pod
metadata:
  name: iso-storage-pod
  namespace: iso
  labels:
    app: iso-storage
spec:
  containers:
  - name: storage
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: iso-storage
      mountPath: /data
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  volumes:
  - name: iso-storage
    persistentVolumeClaim:
      claimName: iso-storage
  restartPolicy: Always
