apiVersion: v1
kind: Pod
metadata:
  name: pvc-init-windows11-disk
  namespace: shalb-dev
spec:
  restartPolicy: Never
  containers:
    - name: init
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          set -euo pipefail
          cd /pvc
          echo "Creating 60G sparse disk.img on PVC..."
          rm -f disk.img || true
          truncate -s 60G disk.img
          chown 107:107 disk.img
          ls -lh disk.img
          echo "Done. Sleeping to allow inspection..."
          sleep 600
      volumeMounts:
        - name: pvc
          mountPath: /pvc
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: windows11-disk
