---
# Kyverno Policy 1: Block Unauthorized Multus Dual-Network
# Prevents pods from using dual-network annotations unless explicitly allowed
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-multus-dual-network
  annotations:
    policies.kyverno.io/title: Restrict Multus Dual-Network Access
    policies.kyverno.io/category: Security, Multi-Tenancy
    policies.kyverno.io/severity: critical
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Prevents unauthorized pods from using Multus dual-network annotations
      (k8s.v1.cni.cncf.io/networks) that could bypass VPC isolation.
      Only system components (vpc-dns) and approved vCluster control planes
      are allowed to use dual-network configuration.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: block-multus-networks-annotation
      match:
        any:
        - resources:
            kinds:
              - Pod
            # Apply to all namespaces with VPC label (project namespaces)
            namespaceSelector:
              matchExpressions:
                - key: vpc
                  operator: Exists
      exclude:
        any:
        # Allow system namespaces
        - resources:
            namespaces:
              - kube-system
              - kube-dc
              - kube-ovn
        # Allow vpc-dns system component
        - resources:
            selector:
              matchLabels:
                ovn.kubernetes.io/vpc-dns: "true"
        # Allow vCluster control plane pods
        - resources:
            selector:
              matchLabels:
                app: vcluster
      validate:
        message: >-
          Dual-network annotations (k8s.v1.cni.cncf.io/networks) are not allowed
          in project VPCs. This would bypass VPC isolation and create a security risk.
          Only approved vCluster control planes and system components may use dual-network.
        deny:
          conditions:
            any:
              - key: "{{ request.object.metadata.annotations.\"k8s.v1.cni.cncf.io/networks\" || '' }}"
                operator: NotEquals
                value: ""

---
# Kyverno Policy 2: Restrict OVN Logical Switch Modifications
# Prevents unauthorized pods from specifying custom OVN logical switches
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-ovn-logical-switch
  annotations:
    policies.kyverno.io/title: Restrict OVN Logical Switch Modifications
    policies.kyverno.io/category: Security, Multi-Tenancy
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Prevents unauthorized modification of OVN logical switch annotations
      that could allow pods to connect to wrong VPCs or networks.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: block-ovn-logical-switch-annotation
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaceSelector:
              matchExpressions:
                - key: vpc
                  operator: Exists
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kube-dc
              - kube-ovn
        - resources:
            selector:
              matchLabels:
                ovn.kubernetes.io/vpc-dns: "true"
        - resources:
            selector:
              matchLabels:
                app: vcluster
      validate:
        message: >-
          OVN logical switch annotations are not allowed. This could allow
          connecting to unauthorized networks or VPCs.
        deny:
          conditions:
            any:
              - key: "{{ request.object.metadata.annotations.\"ovn-nad.default.ovn.kubernetes.io/logical_switch\" || '' }}"
                operator: NotEquals
                value: ""

---
# Kyverno Policy 3: Restrict OVN Routes to Kubernetes API Only
# Allows ONLY routes to Kubernetes API IP (10.101.0.1/32), blocks all other routes
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-ovn-routes-kube-api-only
  annotations:
    policies.kyverno.io/title: Restrict OVN Routes to Kubernetes API Only
    policies.kyverno.io/category: Security, Multi-Tenancy
    policies.kyverno.io/severity: critical
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Allows OVN route annotations ONLY for accessing Kubernetes API (10.101.0.1/32).
      Prevents arbitrary route modifications that could bypass VPC isolation or
      enable lateral movement between networks.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: allow-only-kube-api-route
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaceSelector:
              matchExpressions:
                - key: vpc
                  operator: Exists
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kube-dc
              - kube-ovn
        - resources:
            selector:
              matchLabels:
                ovn.kubernetes.io/vpc-dns: "true"
      validate:
        message: >-
          OVN route annotations are only allowed for Kubernetes API access (10.101.0.1/32).
          The annotation must be exactly: [{"dst":"10.101.0.1/32","gw":"10.100.0.1"}]
          Any other routes are prohibited for security reasons.
        deny:
          conditions:
            any:
              # Block if routes annotation exists but doesn't match the exact allowed pattern
              - key: "{{ request.object.metadata.annotations.\"ovn-nad.default.ovn.kubernetes.io/routes\" || '' }}"
                operator: NotEquals
                value: ""
              - key: "{{ request.object.metadata.annotations.\"ovn-nad.default.ovn.kubernetes.io/routes\" || '' }}"
                operator: NotEquals
                value: '[{"dst":"10.101.0.1/32","gw":"10.100.0.1"}]'
        # Exception for vCluster control plane
        preconditions:
          all:
          - key: "{{ request.object.metadata.labels.app || '' }}"
            operator: NotEquals
            value: "vcluster"

---
# Kyverno Policy 4: Audit Dual-Network Usage
# Creates audit reports for all pods using dual-network configuration
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: audit-dual-network-usage
  annotations:
    policies.kyverno.io/title: Audit Dual-Network Usage
    policies.kyverno.io/category: Security, Audit
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Audits all pods with dual-network configuration for security monitoring.
      Creates policy reports that can be reviewed by security teams.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: audit-multus-networks
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Pod has dual-network configuration via k8s.v1.cni.cncf.io/networks annotation.
          This is audited for security monitoring purposes.
        pattern:
          metadata:
            annotations:
              =(k8s.v1.cni.cncf.io/networks): "?*"
    
    - name: audit-ovn-routes
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Pod has OVN route configuration. This is audited for security monitoring.
        pattern:
          metadata:
            annotations:
              =(ovn-nad.default.ovn.kubernetes.io/routes): "?*"

---
# Kyverno Policy 5: Block Unauthorized StatefulSet Dual-Network
# Prevents StatefulSets from creating pods with dual-network unless approved
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-statefulset-dual-network
  annotations:
    policies.kyverno.io/title: Restrict Dual-Network in StatefulSets
    policies.kyverno.io/category: Security, Multi-Tenancy
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: StatefulSet
    policies.kyverno.io/description: >-
      Prevents StatefulSets from using dual-network pod templates unless
      they have the app=vcluster label (for approved vCluster deployments).
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: block-statefulset-dual-network
      match:
        any:
        - resources:
            kinds:
              - StatefulSet
            namespaceSelector:
              matchExpressions:
                - key: vpc
                  operator: Exists
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kube-dc
        # Allow StatefulSets with vCluster label
        - resources:
            selector:
              matchLabels:
                app: vcluster
      validate:
        message: >-
          StatefulSet with dual-network pod template is not allowed.
          Only vCluster control planes (label: app=vcluster) may use dual-network.
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.template.metadata.annotations.\"k8s.v1.cni.cncf.io/networks\" || '' }}"
                operator: NotEquals
                value: ""
