apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos-base-img
  namespace: demo
spec:
  dataVolumeTemplates:
  - metadata:
      name: centos-base-img
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 15G
        storageClassName: local-path
      source:
        http:
          url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2
  running: true
  template:
    spec:
      networks:
      - name: vpc_net_0
        multus:
          default: true
          networkName: default/ovn-demo
      domain:
        devices:
          interfaces:
            - name: vpc_net_0
              bridge: {}
          disks:
          - disk: 
              bus: virtio
            name: root-volume
          - name: cloudinitdisk
            disk:
              bus: virtio
        machine:
          type: ""
        cpu:
          cores: 1
        memory:
          guest: 4G
      livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 20
        httpGet:
          port: 1500
        timeoutSeconds: 10
      terminationGracePeriodSeconds: 60
      volumes:
      - dataVolume:
          name: centos-base-img
        name: root-volume
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            package_update: true
            package_upgrade: true
            chpasswd: { expire: False }
            password: qweasdz123
            ssh_pwauth: True
            packages:
            - qemu-guest-agent
            runcmd:
            - [ systemctl, start, qemu-guest-agent ]