apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cirros-base-img
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4G
    storageClassName: local-path
  source:
    http:
      url: http://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros-base-img
  namespace: demo
spec:
  running: true
  template:
    spec:
      networks:
      - name: vpc_net_0
        multus:
          default: true
          networkName: default/ovn-demo
      domain:
        devices:
          interfaces:
            - name: vpc_net_0
              bridge: {}
          disks:
          - disk: 
              bus: virtio
            name: root-volume
          - name: cloudinitdisk
            disk:
              bus: virtio
        machine:
          type: ""
        cpu:
          cores: 1
        memory:
          guest: 4G
      terminationGracePeriodSeconds: 60
      volumes:
      - dataVolume:
          name: cirros-base-img
        name: root-volume
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            chpasswd: { expire: False }
            password: qweasdz123
            ssh_pwauth: True
