apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora39-root
  namespace: demo
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15G
    storageClassName: local-path
  source:
    http:
      url: http://mirror.uv.es/mirror/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora39
  namespace: demo
spec:
  running: true
  template:
    spec:
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: my-pub-key
          propagationMethod:
            qemuGuestAgent:
              users:
              - fedora
      networks:
      - name: vpc_net_0
        multus:
          default: true
          networkName: default/ovn-demo
      domain:
        devices:
          interfaces:
            - name: vpc_net_0
              bridge: {}
          disks:
          - disk: 
              bus: virtio
            name: root-volume
          - name: cloudinitdisk
            disk:
              bus: virtio
          rng: {}
        cpu:
          cores: 1
        memory:
          guest: 4G
      readinessProbe:
        guestAgentPing: {} 
        failureThreshold: 10
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
      terminationGracePeriodSeconds: 60
      volumes:
      - dataVolume:
          name: fedora39-root
        name: root-volume
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            chpasswd: { expire: False }
            password: qweasdz123
            ssh_pwauth: True
            package_update: true
            package_upgrade: true
            packages:
            - qemu-guest-agent
            - lrzsz
            runcmd:
            - ["sudo", "sed", "-i", "s/SELINUX=enforcing/SELINUX=disabled/g", "/etc/selinux/config"] # Disable SElinux
            - ["sudo", "setenforce", "0"] # Disable SElinux during init session
            - ["touch", "/tmp/healthy.txt"]
            - ["sudo", "chcon", "-t", "virt_qemu_ga_exec_t", "/tmp/healthy.txt"]
            - ["sudo", "systemctl", "enable", "--now", "qemu-guest-agent"]
