apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: shalb-prod
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: html
          configMap:
            name: nginx-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx!</title>
    </head>
    <body>
        <h1>Test Page Running on Kubernetes</h1>
    </body>
    </html>
