kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: oeip-test-master
spec:
  externalSubnet: external-def
  type: nat
---
kind: OvnFip
apiVersion: kubeovn.io/v1
metadata:
  name: ofip-test-master
spec:
  ovnEip: oeip-test-master
  vpc: shalb-demo
  v4Ip: 10.0.10.139