apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ingress
    meta.helm.sh/release-namespace: shalb-demo
    ovn.kubernetes.io/vpc: shalb-demo
    service.nlb.kube-dc.com/bind-on-default-gw-eip: "true"
    test: test
  creationTimestamp: "2025-05-06T16:11:08Z"
  finalizers:
  - service.kube-dc.com/finalizer
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.12.2
    helm.sh/chart: ingress-nginx-4.12.2
  name: ingress-ingress-nginx-controller
  namespace: shalb-demo
  resourceVersion: "66061"
  uid: bac3b8fc-a303-45c8-a836-7cbe148c3d3f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.1.107
  clusterIPs:
  - 10.101.1.107
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 30178
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 32267
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 168.119.17.50
      ipMode: Proxy