apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-to-https
  namespace: envoy-gateway-system
spec:
  parentRefs:
  - name: eg
    sectionName: http
  hostnames:
  - "*.{{ .variables.domain }}"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
