# HTTP Service Exposure Example
# Exposes a simple web application via HTTP on port 80
#
# Prerequisites:
# - DNS record: my-app.example.com -> Gateway IP (88.99.29.250)
# - Project with cloud networking
#
# Usage:
#   kubectl apply -f 01-http-service.yaml
#
# Test:
#   curl http://my-app.example.com
---
# Sample application deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
---
# LoadBalancer Service with ext-cloud IP
# The controller will auto-create a Backend resource for Gateway routing
apiVersion: v1
kind: Service
metadata:
  name: my-app
  annotations:
    # Bind to project's default gateway EIP
    service.nlb.kube-dc.com/bind-on-eip: default-gw
    # Auto-create Backend for Gateway API routing
    service.nlb.kube-dc.com/create-gateway-backend: "true"
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
# HTTPRoute to expose via shared Gateway
# Routes traffic from Gateway to the Backend (not Service directly)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-app
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    namespace: envoy-gateway-system
    sectionName: http  # Use the HTTP listener on port 80
  hostnames:
  - "my-app.example.com"  # Replace with your domain
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    # Reference the auto-created Backend (service-name + "-backend")
    - group: gateway.envoyproxy.io
      kind: Backend
      name: my-app-backend
      port: 80
