name: update-website

on:
  push:
    branches:
      - main
      - mkdocs
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: write  # This allows GitHub Actions to push to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Use built-in token with write permissions

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: pip install --upgrade mkdocs-material

      - name: Deploy to GitHub Pages
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "github-actions@github.com"
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "github-actions@github.com"
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kube-dc/kube-dc-public.git
          mkdocs gh-deploy --force
